### ISSUE TITLE
Fix non-javascript interaction of some WayFinding components

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#111]
Revealing commands should work without JavaScript.

**Comment by joelcarr** [comment]
Github uses the [`details`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tag for their revealing commands.

![image](https://user-images.githubusercontent.com/893208/40306313-09ce53f6-5cf6-11e8-8301-d728b8d526d2.png)
