### ISSUE TITLE
Introduce the Design System

### ISSUE THREAD

**Issue by olliewright** [barnardos/design-system#129]
_As a user of the design system
I would like clear explanation of what it is, who it is for, and why I should use it
So that I am clear on how to follow the guidelines_

## Acceptance criteria:

- [x] Introduction to what it is
- [x] Explain why it is useful
- [x] Describe who it is for

**Comment by kelliewellingtons** [comment]
Copy for the intro screen

**Barnardo’s Design System**

The Barnardo’s Design System is a central resource that helps you create great digital experiences with us.

- _Principles_
- _Guidance_

This living resource exists to guide, not limit. 

Everyone’s welcome to _contribute_ and give _feedback_.

Future iteration - Add a 'Getting started' nav item and create a induction page.
