### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by olliewright** [barnardos/design-system#131]
_As a user of the Design System, 
I want to know what's changed in it since I last visited
So that I know if I'm up-to-date_

## Description

Consider a strategy for versioning the design system which does not inconvenience developers
And gives people using the design system enough information and reinsurance

## Links and resources

- https://keepachangelog.com/en/1.0.0/

## Acceptance criteria

- [ ] Implement versioning strategy

**Comment by jeddy3** [comment]
This is dependent on https://github.com/barnardos/design-system/issues/220, which has been move to the backlog.
