### ISSUE TITLE
Workshop on the roadmap of the design system

### ISSUE THREAD

**Issue by olliewright** [barnardos/design-system#139]
Workshop to define what the design system will contain both mid-term (Eg. in 3 months) and long-term (Eg. in 6 months+)

**Acceptance Criteria**
- [ ] A document that details the scope of the design system
- [ ] NOW | NEXT | LATER |

**Comment by olliewright** [comment]
@jeddy3 @kelliewellingtons @sl33p - notes from our meeting are below.

Richie, Kellie - let me know when you are both free and together we can finish the category headers, and place the relevant bullets beneath them.

Suggested categories headers when describing the vision:

**Vision
Principles
Definition of success
Objectives
Criteria for inclusion
Long term goals**

Suggested bullet points:

- To deliver value quickly

- To be able to complete your task the first time unaided
- To use the design system to build your product confidently unaided

- Ask people what they want from the Design System
- Reach as many people as possible and track who we have met with, and what their needs are
- Reach as many people as possible and make sure they know how to use it
- To always validate the Design System against children and young people 
- If research starts from a desk first, always research together with real people afterwards

- To be flexible to be iterated at any point, with no need to un-pick code when technology improves in the future
- To be flexible to be iterated at any point, with no need to un-pick code if / when technical feedback is given
- Components should be re-useable across the organisation(s)

- Work should be prioritised
- Work should be prioritised by estimated value

Assumptions:
- Implementation of the design system increases efficiency for Barnardo's and services
- Implementation of the design system reduces costs for Barnardo’s
- Implementation of the design system increases consistency

NOW | NEXT | LATER

NOW
Writeup the vision statements
Create document to track which services and people we have met, bullet point their requirements

NEXT
The vision statements need to be somewhere visible to the wider Barnardo’s organisation/staff
The vision statements need to be somewhere visible to the users of the Design System
To always validate the Design System against children and young people 

LATER
Dedicated sprints to the advocacy of the product in Q4
Installing all the tools needed with 1 service in Q4
Align 5 x services to the design system by X date
Set the process of the handover at the end of Q4, in steps

If there is nothing else to add to the notes, I will take the above and start a document for us to work from and close this issue.

**Comment by kelliewellingtons** [comment]
I've reworded and reordered the bulleted list in the vision doc for review.

**Comment by olliewright** [comment]
@kelliewellingtons can you please confirm with @jeddy3 that he is also happy with your refined bullet points in https://docs.google.com/document/d/1ifuJALMIFTZIjtte5pfcHUvtY3r-kjmya-uo2vRhXQA/edit and then add this vision to the Design System?

We can then close this ticket. And @sl33p and I will open a new one to create an infographic roadmap for NOW | NEXT | LATER to help us structure the next 5 months (as well as bring the wider organisation into the loop with the plans for The Design System at the July Lunch and Learn).

**Comment by jeddy3** [comment]
> @jeddy3 that he is also happy with your refined bullet 

The list looks good as a foundation to me.

> and then add this vision to the Design System?

I'll create a follow-up user story issue for actually adding the vision to the Design system.

> We can then close this ticket.

Yep, we can close this now as the workshop is complete and an artefact produced :)
