### ISSUE TITLE
Create accessible colour palette

### ISSUE THREAD

**Issue by sampling** [barnardos/design-system#14]
_As a user of the design system
I want to use accessible colours
So that I can cater for all my users_

## Description

In order to created a single source of truth for a web colour palette, all existing uses of the palette will be audited and pulled together.

The creative team and website team will be involved to ensure everyone is in agreement with the selection going forward.

Chosen colours must be AA compliant.

## Acceptance Criteria

- [x] Create the palette

**Comment by jeddy3** [comment]
Closing. Implementation happening in https://github.com/barnardos/design-system/issues/19

**Comment by kelliewellingtons** [comment]
The following updates are required:
- Orange stands out as too luminous in relation to other colours, tweak to: #e86c00
- Pink stands out as too luminous in relation to other colours, tweak to: #be0068
- Red needs to be darker to be AA compliant, tweak to: #c30000
- Black need to be updated to the accurate colour being used, tweak to: #1D1D1D

Should the colour names be sentence case?
Should the suggested usage paragraphs be sentence case?
