### ISSUE TITLE
Add developer philosophies 

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#150]
_As a developer using the Design System,
I want to see the detail on the philosophies of how the Design System has been created,
So that I can follow similar philosophies._

Relates to #183

**Comment by jeddy3** [comment]
Includes:

- code quality tools
- locking down CSS with stylelint so that the use of each feature is reasoned about

**Comment by jeddy3** [comment]
I've added an estimate of 5. I don't think it's a big piece of work. It just hasn't been a priority yet.

**Comment by kelliedesigner** [comment]
This was covered on in #183
