### ISSUE TITLE
Fix optimal line length

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#156]
The initial version of the Typography section references [material.io](https://material.io/design/typography/understanding-typography.html) which states:
> The ideal line length is 40-60 characters per line for English body text.

Feedback from teams using this guidance has been that when trying to implement this rule, the line length has been too constrained.

This ticket is to research optimal line length further and improve guidance on the rule.

**Comment by jeddy3** [comment]
On further desk research, there appears to be a broader range:

- https://practicaltypography.com/line-length.html
- https://www.usability.gov/get-involved/blog/2006/08/line-length-and-onscreen-reading.html
- https://graphicdesign.stackexchange.com/questions/13724/recommended-column-width-for-text-reading-digital-vs-printed

The practical purpose of the line length guidance to was have teams avoid _very_ short and _very_ long lines. As such, I think we can broaden the _optimal_ range from 45-95.
