### ISSUE TITLE
How to gather currency data

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#160]
_As a user of the design system
I want to know how to gather currency data
So that there is a consistent experience across services_

## Description

The user needs to enter a monetary value.

## Links and resources

- https://blog.mobiscroll.com/currency-input-on-mobile/
- http://uipatterns.io/currency-input

## Acceptance Criteria

- [ ] Add components to design system
- [ ] Addresses accessibility/usability considerations
- [ ] Works on target devices and browsers

**Comment by jeddy3** [comment]
Flexbox is good CSS Layout solution here:
https://philipwalton.github.io/solved-by-flexbox/demos/input-add-ons/
