### ISSUE TITLE
Develop templates for the following components for Facebook workshop

### ISSUE THREAD

**Issue by Jesskyri** [barnardos/design-system#162]
Here are the list of component/ elements I want to test for the Facebook workshop. 

Need to create some icons/ templates as stimuli:

https://docs.google.com/spreadsheets/d/1fszLdDmPN26nZ6PKuKPNLnDIlF2Fm8oLRLo-vZrB62E/edit#gid=0

**Comment by kelliewellingtons** [comment]
All assets have been created and sent to printers
