### ISSUE TITLE
Add accessibility guidance

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#168]
_As a user of the design system
I want to know how to include the widest range of users possible,
So that there is an inclusive experience across services_

## Links and resources
- https://github.com/barnardos/accessibility-lunch-talk
- https://github.com/barnardos/accessibility-lunch-talk/blob/master/pdf/talk.pdf

## Acceptance Criteria

- [ ] Add guidance to design system

**Comment by kelliewellingtons** [comment]
When considering accessibility, you should:
* think about how users might access and use your product before you design or build anything
* follow the [WCAG scoring process](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)
* continue to test against criteria throughout building the product
* use the components in the Design System

Common things to look out for are:
* contrast
* being able to navigate with a keyboard
* content is easy to read and understand
* it can be zoomed to 200%
* images use an alt attribute
* headings are in hierarchical order
* browser page titles are unique and descriptive
* forms are labelled with 'for' and 'id' attributes
* pages have the language defines through a 'lang' attribute

Resources
* [WCAG](https://www.w3.org/WAI/standards-guidelines/wcag/) Web Content Accessibility Guidelines
* [Wave evaluation tool for Chrome](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)
* [Web AIM colour contrast checker](https://webaim.org/resources/contrastchecker/)

**Comment by jeddy3** [comment]
From [Semantics to screenreaders](https://alistapart.com/article/semantics-to-screen-readers/):

> As web developers, we don’t necessarily need to make sure that each instance surfaces information identically, because each user’s preferences will not be exactly the same. Our aim is to ensure that no matter how a user chooses to explore our sites, content is perceivable, operable, understandable, and robust. By testing with a variety of assistive technologies—including but not limited to screen readers—we can help create a better web for all the many people who use it.

**Comment by kelliedesigner** [comment]
Key findings from [Medium](https://medium.com/myplanet-musings/comparing-3-top-automated-accessibility-testing-tools-wave-tenon-io-and-google-lighthouse-d3897d7bb311)
> * Google Lighthouse is available as a node module that can be used on the command line or within a continuous integration environment, and has the distinct advantage of being free, which makes it a good candidate for projects with no budget for accessibility.
