### ISSUE TITLE
Decide on feedback loop

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#177]
_As a user of the design system
I want to know how to give my feedback,
SO that I feel empowered to contribute and it can be improved_

## Acceptance Criteria

- [ ] Decide which feedback loop to use in the design system

**Comment by kelliewellingtons** [comment]
Gov.uk
<img width="986" alt="screen shot 2018-06-22 at 16 32 59" src="https://user-images.githubusercontent.com/6122118/41785305-1311f33e-763a-11e8-947c-5481af605e61.png">

**Comment by kelliewellingtons** [comment]
Coop
<img width="672" alt="screen shot 2018-06-22 at 16 33 29" src="https://user-images.githubusercontent.com/6122118/41785314-1c561434-763a-11e8-9370-4eed16ab510a.png">

**Comment by kelliedesigner** [comment]
A kick-off meeting has been arranged for Friday 17th

**Comment by kelliedesigner** [comment]
Meeting rescheduled to 21st

**Comment by kelliedesigner** [comment]
Actions from kick-off:
- We'll get access to the Hotjar account to view the products that currently use it, and their success
- Add Hotjar to the Design System
- Ellen to speak to Nick about why Hotjar was chosen, and if we could instead create a bespoke feedback loop (eg Co-op)
- @jeddy3  to provide a view on the complexity of building a bespoke feedback loop, and what would the simplest version be, for example, a form that sends feedback to an email mailbox.

<img width="664" alt="screen shot 2018-08-21 at 11 02 08" src="https://user-images.githubusercontent.com/6122118/44395393-ada43300-a531-11e8-8f4a-2bdc8a712d63.png">

**Comment by e-booker** [comment]
@kelliedesigner, @jeddy3 

Sorry for the long message, but I'm not in again until Wednesday so wanted to record this here.

I've got access to the hotjar account & been digging. There are a few options, but I am keen on 2 - if you agree.

**Options**

I've created:

1. a on-page feedback option - as on rh of https://www.barnardos.org.uk/who-we-are/our-corporate-strategy - where users can respond to a question with a 1 to 5 rating

2. an on-page survey - as https://help.hotjar.com/hc/en-us/articles/115011772568-How-do-Hotjar-Polls-Work- - which looks like our best option for a simple 'Did you find what you were looking for?' question with a yes/no answer - it's also possible to add a follow-up question & email collect

3. a recruiter option - https://help.hotjar.com/hc/en-us/articles/115011761548-How-do-Hotjar-Recruiters-Work- - which could be useful to find potential research participants

**Proposal**

If you're happy to, I'd be keen to test option 2 on - as well as in - the design system? It could:

- inform any development we might need for a bespoke feedback mechanism

- encourage feedback on 1 (or more) elements of the design system

- help me to see how it works in practice - before I have the live transformation content to measure

**What do you think?** 

If you like the idea, next steps are: 

- [ ] @e-booker to add https://barnardos-design-system.netlify.com/ to the hotjar account

- [ ] add the tracking code (below) to the site - instructions at https://help.hotjar.com/hc/en-us/articles/115009499088-The-Hotjar-Tracking-Code

- [ ] @e-booker to verify the addition

- [ ] collectively review the on-page question we ask & the notification method we want if someone responds

- [ ] start tracking

- [ ] agree a review point to evaluate

[tracking code]


<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:991092,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by e-booker** [comment]
Also, sorry (!), let's speak next week if you have questions!

**Comment by mat-walker** [comment]
Nice idea but in my experience of adding those polls to the Barnardo’s website you’ll be waiting a *very* long time before you get any meaningful feedback

Thanks,

Mat

**Comment by jeddy3** [comment]
> @jeddy3 to provide a view on the complexity of building a bespoke feedback loop, and what would the simplest version be, for example, a form that sends feedback to an email mailbox.

Netlify offers [a way of processing forms](https://www.netlify.com/docs/form-handling/) on static sites (which is pretty rad). It looks so-so simple, we'd get email notification of submits and we can style the form using components from the Design System.

However, Matt's experience casts doubt on the value of putting any effort into implementing an interactive feedback loop, whether via Netlify or HotJar.

I believe a significantly easier solution than an interactive feedback loop would be adding a (non-interactive) copy block on each page requesting feedback via email or Workplace.

We hit on this on the bottom of the [Getting started page](https://barnardos-design-system.netlify.com/getting-started/), but we can also emphasis it on each page too.

GDS seem to have adopted this approach in their latest [Design System](https://design-system.service.gov.uk/components/error-message/).
