### ISSUE TITLE
Add tooling

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#183]
_As a user of the design system
I want to know what tools I can use to check my code,
SO that my code quality is consistent with the other products being developed_

Relates to #150 

## Acceptance Criteria

- [ ] Add tooling to Design System documentation

**Comment by jeddy3** [comment]
- pretty print your code using prettier (default settings)
- lint your css using stylelint (barnardo's shared config, which builds on recommend config)
- lint your javascript using eslint (recommended config)

Write future-facing code and transpile your:
- javascript with babel (with babel-preset-env)
- css with postcss (postcss-preset-env)

Using browerslist to configure both.

**Comment by jeddy3** [comment]
From [Testing 2019 roundup](https://medium.com/@me_37286/yoni-goldberg-javascript-nodejs-testing-best-practices-2b98924c9347#49f5)

> Linters are a free lunch, with 5 min setup you get for free an auto-pilot guarding your code and catching significant issue as you type. Gone are the days where linting was about cosmetics (no semi-colons!). Nowadays, Linters can catch severe issues like errors that are not thrown correctly and losing information

**Comment by jeddy3** [comment]
From [Why Prettier?](https://prettier.io/docs/en/why-prettier.html): 

> By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles. It is [generally accepted that having a common style guide is valuable for a project and team](https://www.smashingmagazine.com/2012/10/why-coding-style-matters/) but getting there is a very painful and unrewarding process. People get very emotional around particular ways of writing code and nobody likes spending time writing and receiving nits.

> So why choose the "Prettier style guide" over any other random style guide? Because Prettier is the only "style guide" that is fully automatic. Even if Prettier does not format all code 100% the way you'd like, it's worth the "sacrifice" given the unique benefits of Prettier

**Comment by jeddy3** [comment]
From [Lint your CSS with stylelint - on CSSTricks](https://css-tricks.com/stylelint/):

> You write CSS. Probably a lot of CSS. And you make mistakes. Probably a lot of mistakes. Somebody needs to stop you from making mistakes in your CSS.

> Sometimes your mistake is a real bug. Sometimes it's just sloppy, inconsistent, or unclear coding style. Some of them may seem trivial at first (depending on your temperament), but they become patently important as the codebase grows and ages, as more people stick their hands in it and do ugly things. Things you thought unimaginable.

> You try to control yourself. Your colleagues pitch in, too, correcting you when you stray. But both you and your colleagues are mistake-makers, so will naturally, inevitably fail, at least in part. And later on you or some other sorry sap will face the consequences of those mistakes that slipped into your CSS.

> Additionally, you'd much rather be corrected right away than wait for a code review just so someone can point out that you duplicated a declaration and should clean up your spacing. Instant feedback would help you internalize conventions and spend a little less time floundering when your CSS doesn't work.

**Comment by jeddy3** [comment]
From [Side Effects in CSS](https://philipwalton.com/articles/side-effects-in-css/):

> The problem with mixing non-BEM features in with BEM is they can often destroy the safety net BEM creates for you. BEM is effective not because it gives you a bunch of options, but because it limits what you’re allowed to do. It prevents you from shooting yourself in the foot. All of BEM’s rules exist for good reason, and if you’re going to suggest changing them, you’d better know what those reasons are.

**Comment by jeddy3** [comment]
ESLint is the defacto JavaScript linter. It has plugins for frameworks and libraries, including React and Jest. It's built-in `recommended` config turns on the built-in _error checking_ rules and stays away from the _stylistic_ rules. This is good for us as we off-load _pretty-printing_ to Prettier for [good reasons](https://github.com/barnardos/design-system/issues/183#issuecomment-461804955?). Additionally, Prettier also supports most frontend languages including JavaScript, Markdown, CSS and JSON.

**Comment by jeddy3** [comment]
stylelint is a pluggable linter for styles. It allows us to:

- use plugins to enforce BEM conventions
- use custom plugins to enforce design system rules like 0.25rem multiples for spacing
- detect subtle mistakes like overriding shorthand properties
- opt-in to a small subset of the CSS language it to keep things consistent and easy to use/learnCSS
- enforce conventions that make it easier to collaborate and review code liked ordered declarations

We use a subset of the CSS language to help us manage complexity. We started out by not whitelisting any CSS language features, e.g. no properties, functions, pseudo-classes or units were allowed. Over time we've [whitelisted the features](https://github.com/barnardos/stylelint-config-barnardos/blob/master/index.js) we need. This approach enables us to reason about each part of the language we use.
