### ISSUE TITLE
How to know your location and navigate the site

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#2]
_As a user of the design system
I want to know how to communicate location and navigation
So that there is a consistent experience across sites_

## Description

The aim of a global navigation is to:
- switch between top-level categories easily, no matter their current location
- get a sense of what is available on the website even if they don't enter via the homepage
- communicate the brand

## Links and resources

- Related global footer and header spike: https://github.com/barnardos/digital-transformation/issues/80

## Acceptance Criteria

- [x] Addresses accessibility/usability considerations
- [x] Works on target devices and browsers

Elements to consider:
- [x] Rules for Logo (homepage versus drilled down pages)
- [x] Global navigation/menu/when to display navigation v when to collapse
- [ ] Rules for primary/secondary/tertiary items
- [x] Adaptation for smaller viewports, while retaining the underlying universal rules
- [x] Search
- [ ] Sign in/Sign up admin links
- [ ] With/without imagery
- [x] Adaptations for microsite
- [x] Responsive considerations

**Comment by jeddy3** [comment]
Research [from NN on](https://www.nngroup.com/articles/hamburger-menus/):

> Our quantitative usability testing of hidden menus (such as hamburger icons) and visible menus (such as links across the top of pages) reveals that:
> - Hidden navigation is less discoverable than visible or partially visible navigation.
>   - When navigation is hidden, users are less likely to use navigation.
>   - If people use hidden navigation, they do so later in the task than if it were visible.
> - Hidden navigation provides a worse user experience than visible or partially visible navigation does, in both mobile phones and desktop user interfaces. This finding holds true across multiple UX metrics including users’ assessment of task difficulty, time spent on task, and task success.
> - On desktops, hiding navigation degrades the experience and the navigation discoverability more than it does on the phones.

**Comment by jeddy3** [comment]
Research from [What Users Do](http://whatusersdo.com/blog/hamburger-menus-damage-ux)

>There is plenty of screen real estate for displaying navigation options, and we recommend:
>
> - Not to use hidden navigation (such as hamburger icons) in desktop user interfaces
> - Instead,

 display the top-level navigation options, usually across the top of the page or down the left side

**Comment by jeddy3** [comment]
[NN group](https://www.nngroup.com/articles/text-over-images/) findings on text over images:

> ensure that the text is both legible and readable to users. (As a reminder, legibility refers to the ability to distinguish the individual characters, while readability refers to the ability to actually process the meaning of the words.) 

> Use effects such as a semiopaque overlay (either covering the entire image or just the text portion), a blur, a text shadow or outline, or a combination of these techniques. Remember that it’s not enough to make it possible for people to use the site, which is the definition of accessibility.

**Comment by kelliewellingtons** [comment]
Findings from [NN](https://www.nngroup.com/articles/killing-global-navigation-one-trend-avoid/) on hiding global navigation

**Comment by kelliewellingtons** [comment]
Key findings from [IDF](https://www.interaction-design.org/literature/article/implement-global-navigation-to-improve-website-usability)

> - When you’re designing a new website, application, or other product, you always start with the global idea and structure before addressing more detailed issues.
> - Users need content to be provided with some means of navigating between different groups of content and returning back to their starting position
> - The vast majority of users will know how to interact with the global navigation design pattern. Arranging content or category labels along the top helps give the users an overview of the user interface and informs them of where they can go and how they can get there.


When designing a global navigation:
> - Reserve the space for buttons, links, search bars, and elements affording movement from one set of content to another
> - Keep it identical in appearance across all different pages to provide a consistent means of travelling
> - Keep to a maximum of 12 items, to avoid overcrowding and a decrease in usability.

**Comment by kelliewellingtons** [comment]
Good example of balancing communicating the brand, while providing consistent and visible top-level navigation.

> - Large branding is displayed, but transitions to a smaller functional size when content takes precedence for the user
> - Type presented over imagery uses block colour to ensure legibility, and thematic consistency when the type is dropped below the image on smaller viewport sizes
> - Global navigation is visible on larger viewports and only moves under a hamburger menu on smaller viewport sizes

![screen-shot-2018-03-22-at-16 23 30](https://user-images.githubusercontent.com/6122118/37784188-1cf7d0be-2def-11e8-9fad-38dd061bc617.png)

![unicef-mobile-screen-shot-2018-03-22-at-16 24 53](https://user-images.githubusercontent.com/6122118/37784214-2588091a-2def-11e8-9f9a-11e4a41ec66e.png)

**Comment by kelliewellingtons** [comment]
Key findings from [10 Principles Of Navigation Design And Why Quality Navigation Is So Critical](https://onextrapixel.com/10-principles-of-navigation-design-and-why-quality-navigation-is-so-critical/)

> - Navigation is critical for large content sites.
> - The over-riding design principle is functionality, not style. It should always be simple, direct, unadorned
> - Navigation should be integrated with search, kicking in to provide context for their search

> **- Let readers know where they are**
> Give a clear and unambiguous indication of what page they're on. 
>
> **- Let readers know where they’ve been**
> Use the standard colours for hypertext (blue for unclicked links, and purple for clicked).
>
> **- Let readers know where they are going**
> Change the link colour on hover so they know which link they're about to select.
> Inform them in advance if you intend for them to go anywhere other than a HTML page (eg PDF download).
>
> **- Follow web convention**
> Design for the reader, avoid designing navigation simply for it to look good. A number of navigation conventions have emerged on the Web. The designer who deliberately avoids these conventions, just to be different, achieves nothing except to confuse the reader.

**Comment by kelliewellingtons** [comment]
Key findings from [UX Booth](http://www.uxbooth.com/articles/the-rules-for-modern-navigation/)

**The Rules for Modern Navigation**

> Design a navigation that:
> - Prioritises consistency and sticks to universal rules
> - Has clear interactions
> - allow users to quickly understand which links are primary, secondary, and tertiary navigation items.
> - Has a limited number of levels (maximum of 4 if possible)
> - doesn't require people to adjust to a different mental model when moving from desktop to mobile.

**Comment by kelliewellingtons** [comment]
Key findings from [NN](https://www.nngroup.com/articles/mobile-first-not-mobile-only/)

**Mobile First Is NOT Mobile Only**

> - Hiding navigation under a menu significantly decreases the use of the navigation and also degrades the overall user experience both on desktop and on mobile.
>
> - Hiding navigation under an expandable menu can be a necessity on a small mobile device
>
> - Expandable navigation (such as the hamburger menu) was the biggest offender and certainly the mobile-inspired pattern most relevant to our study. We’ve seen from many qualitative studies that it doesn’t work on the desktop, but sites still insist on using it.
>
> - One of the desktop sites placed the navigation in a highly nonstandard position for the desktop: the top right corner.
>
> - Many of the sites also got rid of the search box on the desktop and preferred to use a search icon instead. We generally recommend against this practice on the desktop; we’ve heard countless users complaining about having to locate a tiny icon on a large screen.

**Comment by ritapatel7** [comment]
Strongly agree with the above, need nav showing on desktop rather than under a burger menu so I know immediately what is on the website and what I need.

**Comment by kelliewellingtons** [comment]
Key findings from [UX Planet](https://uxplanet.org/breadcrumbs-for-web-sites-what-when-and-how-9273dacf1960)

Use breadcrumbs when you have a large amount of content organized in a strict linear structure or hierarchical structure with defined categories

**Breadcrumb Navigation Best Practices**
> - Don’t Use Breadcrumbs As a Replacement For the Primary Navigation
> - Don’t Include Link to the Current Page in Navigation
> - Use Separators, for example '>' or '/'
> - Don't allow them to dominate the page or overpower the primary navigation
> - Don’t Make It the Focal Point of the Design

**Comment by jeddy3** [comment]
Findings from [Madison Ave. Collective](https://medium.com/madison-ave-collective/are-breadcrumbs-still-fresh-for-ux-6e72b0f96e9b):

> - Use breadcrumbs when designing websites that are three or more levels deep
> - Place breadcrumbs directly above or next to the page title
> - Use arrows — not slashes or vertical lines — to imply movement between pages or point back home
