### ISSUE TITLE
Research how to treat text over imagery

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#208]
_As a user of the Design System
I want to know how to treat text over images
So that I can create an accessible and consistent experience_

## Description

Displaying headline text over imagery is a common problem across products, and posing several challenges around accessibility and implementation.

## Links and resources

* https://www.savethechildren.org.uk/
* https://www.unicef.org.uk/

Website:
<img width="527" alt="screen shot 2018-07-04 at 10 19 44" src="https://user-images.githubusercontent.com/6122118/42268617-e21b13f8-7f73-11e8-9a64-42ec01ef8e40.png">

## Acceptance Criteria

* [ ] Research the optimal solution for treating text over imagery

**Comment by kelliewellingtons** [comment]
Text highlight:
https://blog.iamsuleiman.com/techniques-to-display-text-overlay-background-images/
<img width="650" alt="screen shot 2018-07-04 at 10 32 38" src="https://user-images.githubusercontent.com/6122118/42269278-a92ccef4-7f75-11e8-8e6c-07b381535bbe.png">

**Comment by kelliedesigner** [comment]
StC also uses this treatment on smaller call out images:
![image uploaded from ios 2](https://user-images.githubusercontent.com/6122118/42318580-58432862-8047-11e8-8fde-8495c72cc2fe.png)

**Comment by kelliedesigner** [comment]
Research has been completed and shared with the team that requested it.

A subsequent issue will be created and prioritised to use the research and create relevant components in the Design System.
