### ISSUE TITLE
Add how to display typographic statistics

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#212]
_As a user of the Design System
I want to know how to display typographic statistics
So that I can solve the user need to emphasise facts and other information and maintain consistency with other products_

## Links and resources

* https://www.unicef.org.uk/donate/
* https://govuk-elements.herokuapp.com/data/

## Acceptance Criteria

* [ ] Add components to design system
* [ ] Addresses accessibility/usability considerations
* [ ] Works on target devices and browsers

**Comment by kelliewellingtons** [comment]
Unicef:
<img width="533" alt="screen shot 2018-07-04 at 14 10 20" src="https://user-images.githubusercontent.com/6122118/42278912-13f79f5c-7f94-11e8-8059-dde599479ae7.png">

<img width="485" alt="screen shot 2018-07-04 at 14 10 27" src="https://user-images.githubusercontent.com/6122118/42278918-1713e0f6-7f94-11e8-92ae-156ac97647aa.png">

**Comment by kelliewellingtons** [comment]
Gov.uk:
<img width="272" alt="screen shot 2018-07-04 at 14 10 46" src="https://user-images.githubusercontent.com/6122118/42278933-200b2480-7f94-11e8-924c-1c68774f7551.png">

**Comment by kelliedesigner** [comment]
Barnardo's Impact report:
![screen shot 2018-07-30 at 11 31 15](https://user-images.githubusercontent.com/6122118/43395022-8df4d90e-93f4-11e8-9939-2ca76a275ee2.png)

![screen shot 2018-07-30 at 11 26 40](https://user-images.githubusercontent.com/6122118/43395028-91732ee6-93f4-11e8-875b-c2c0557afbe5.png)

**Comment by kelliedesigner** [comment]
In-progress Barnardo's product:
![pie-chart](https://user-images.githubusercontent.com/6122118/44151016-2f8c3bee-a099-11e8-9d24-4027039a9400.png)

**Comment by kelliedesigner** [comment]
2017 Impact Report:
<img width="843" alt="screen shot 2018-09-04 at 16 23 45" src="https://user-images.githubusercontent.com/6122118/45041069-5937a200-b05f-11e8-92eb-ee343bd59758.png">

**Comment by kelliedesigner** [comment]
Oxfam 2015/16 annual report
<img width="410" alt="screen shot 2018-09-20 at 10 15 52" src="https://user-images.githubusercontent.com/6122118/45808657-3db6d300-bcbe-11e8-8620-4b8c8f394cd9.png">

**Comment by kelliedesigner** [comment]
Save the Children 2016 annual report:
<img width="310" alt="screen shot 2018-09-20 at 10 18 59" src="https://user-images.githubusercontent.com/6122118/45808806-a2722d80-bcbe-11e8-88e1-3e85472a694e.png">

**Comment by kelliedesigner** [comment]
RNLI 2017 annual report:
<img width="256" alt="screen shot 2018-09-20 at 10 34 31" src="https://user-images.githubusercontent.com/6122118/45809779-f7af3e80-bcc0-11e8-9000-f341e7eda9ac.png">

**Comment by kelliedesigner** [comment]
Red Cross Trustees’ report and accounts 2017:
<img width="206" alt="screen shot 2018-09-20 at 10 41 39" src="https://user-images.githubusercontent.com/6122118/45810130-d7cc4a80-bcc1-11e8-901e-87ca136b5d26.png">

**Comment by kelliedesigner** [comment]
RSPCA Trustees’ report and accounts 2016:
<img width="420" alt="screen shot 2018-09-20 at 10 54 07" src="https://user-images.githubusercontent.com/6122118/45810855-96d53580-bcc3-11e8-9b02-56eeac2c1e77.png">
