### ISSUE TITLE
Add how to display secondary navigation

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#219]
_As a user of the Design System
I want to know how to display secondary navigation
So that I create a consistent experience across products_

## Links and resources

* Relates to: How to know your location and navigate the site #2 
* http://bradfrost.com/blog/web/responsive-nav-patterns/
* https://www.actionforchildren.org.uk/

## Acceptance Criteria

* [x] Research the optimal way to display secondary navigation

**Comment by kelliedesigner** [comment]
Action for children:
<img width="1280" alt="screen shot 2018-07-09 at 17 50 21" src="https://user-images.githubusercontent.com/6122118/42464323-9800f40a-83a0-11e8-9ab3-52d656220e2b.png">

**Comment by kelliedesigner** [comment]
Key points from [UX Booth](http://www.uxbooth.com/articles/the-rules-for-modern-navigation/):

> **Unique Visual Design for Each Level**
> People should be able to quickly scan the navigation and understand which links are primary, secondary, and tertiary navigation items.

> **Remove Hover Interactions**
> Primary navigation often displays the secondary links on hover; however it doesn’t always work for mobile. Utilizing a hover interaction that can’t be used on mobile introduces inconsistency between the two devices.

**Comment by jeddy3** [comment]
[NN Group on home links](https://www.nngroup.com/articles/homepage-links/):

> A site logo linking to the homepage is not enough. Logo design and placement, as well as the presence of a text link to the homepage affect success of navigation to homepage.

**Comment by kelliedesigner** [comment]
Simplest solution which minimises code complexity while providing the best user experience:
* On larger viewports, display all primary nav items in a horizontal row
* Secondary items are presented horizontally a row below, accessible on click of a primary nav item, which takes you to a landing page
* As the viewport reduces and hits the breakpoint, the navigation is converted into a burger menu
* On click, the menu opens from the left and displays both the primary and secondary nav items, with a scroll

**Comment by kelliedesigner** [comment]
Research has been completed and shared with the team that requested it. 

A subsequent issue will be created and prioritised to use the research and create relevant components in the Design System.

**Comment by kelliedesigner** [comment]
RNLI:
![screen shot 2018-07-25 at 14 38 56](https://user-images.githubusercontent.com/6122118/43204435-b65e4946-9018-11e8-8f8f-eda93ebaa124.png)

![screen shot 2018-07-25 at 14 39 16](https://user-images.githubusercontent.com/6122118/43204443-bb7f0cb2-9018-11e8-8c3c-76147689988b.png)

**Comment by kelliedesigner** [comment]
Barnardo's Impact Report secondary navigation:
![screen shot 2018-07-30 at 11 30 21](https://user-images.githubusercontent.com/6122118/43394482-d2c0133e-93f2-11e8-9f51-ff74384610a5.png)
