### ISSUE TITLE
How to treat iconography

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#226]
_As a user of the Design System
I want to know how to treat iconography
So that there is consistency across products_

## Description

**Iconography, animation and illustration** 

Iconography:
* have a flat graphic style
* use the colour palette 
* avoid relying on icons to convey important information

## Acceptance Criteria

* [ ] Add iconography, animation and illustration section into the Design System

**Comment by jeddy3** [comment]
Findings from [NN Group](https://www.nngroup.com/articles/icon-usability/):

> Due to the absence of a standard usage for most icons, text labels are necessary to communicate the meaning and reduce ambiguity.

**Comment by jeddy3** [comment]
Using colour and flat icons from Barnardo's brand guidelines.
