### ISSUE TITLE
Fix redundant "intranet" item in writing guidance

### ISSUE THREAD

**Issue by tosbourn** [barnardos/design-system#228]
In [writing content](https://barnardos-design-system.netlify.com/guidance/writing-content/) we talk about the correct way to say "intranet".

In a recent board walk it was shared that we should be referring to that as "Inside.Barnardo's" I wonder if we should be advising that here. If we consistently use the correct term internally it will help with any external communication.

I've checked with Carrie Swatten and the full stop is correct.

**Comment by kelliedesigner** [comment]
Proposed solution is to remove the bullet that refers to 'intranet', as this is a list of spellings rather than product names, and the term 'intranet will no longer be used, therefore guidance on spelling is redundant.
