### ISSUE TITLE
Fix Accessibility Testing guidance

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#249]
* [x] Update Axe link to Lighthouse: https://developers.google.com/web/tools/lighthouse/
* [x] Update Axe text to Lighthouse
* [x] Remove keyboard tabbing bullet
* [x] Add go through Lighthouse's manual accessbility checks

**Comment by kelliedesigner** [comment]
Feedback from the cyp workshop included ensuring that font sizes and colours of digital products can be adapted without compromise to the design.

Gov.uk blog post on this topic:
https://accessibility.blog.gov.uk/2017/03/27/how-users-change-colours-on-websites/

**Comment by kelliedesigner** [comment]
Feedback from the cyp workshop:
- Emoji's sometimes have better descriptions that allow users with visual impairments to picture a situation more than photographs.
- "include clear written descriptions in the code" or something like this.

**Comment by jeddy3** [comment]
Feedback from chat with GDS:

1. Start by checking the [Accessibility Tree](https://developers.google.com/web/fundamentals/accessibility/semantics-builtin/the-accessibility-tree)
2. Test tab order with a screen reader
