### ISSUE TITLE
Add progress link

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#282]
_As a user of the Design System
I want to know how to treat a link which progresses to another page
So that there is consistency across products_

## Description

There is a need for a type of link which provides a call to action that indicates to the user that they'll be progressing to find out more about the same theme of content.

It is to fill the gap between Pagination, Start Link and a standard link.

## Links and resources

* https://barnardos-design-system.netlify.com/guidance/navigating/

## Acceptance Criteria

* [ ] Add components to design system
* [ ] Addresses accessibility/usability considerations
* [ ] Works on target devices and browsers

**Comment by jeddy3** [comment]
Findings from [NN Group](https://www.nngroup.com/articles/learn-more-links/) on text of links:

> Summary: The phrase ‘Learn More’ is increasingly used as a crutch for link labels. But the text has poor information scent and is bad for accessibility. With a little effort, transform this filler copy into descriptive labels that help users confidently predict what the next page will be.

**Comment by jeddy3** [comment]
Findings from [NN Group](https://www.nngroup.com/articles/guidelines-for-visualizing-links/) on visualising links:

> Summary: Textual links should be colored and underlined to achieve the best perceived affordance of clickability, though there are a few exceptions to these guidelines.

**Comment by kelliedesigner** [comment]
Barnardo's Impact Report 2018:
<img width="1027" alt="screen shot 2018-10-23 at 12 33 57" src="https://user-images.githubusercontent.com/6122118/47357905-0e7df200-d6c0-11e8-8702-cdbb9dcdda1f.png">
