### ISSUE TITLE
Report build errors not showing in browser

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#284]
## Description

Gatsby is no longer showing build errors, only a blank page.

## Step to reproduce

1. Create an error, for example reference a component without importing it
2. View local version of the deploy

## Acceptance criteria

[ ] Report this error to Gatsby

**Comment by jeddy3** [comment]
Let's wait from Gatsby@2 proper to be released in the home this is addressed up stream.

**Comment by jeddy3** [comment]
Fixed.
