### ISSUE TITLE
Add CYP specific information

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#294]
_As a user of the Design System
I want to know how to create products for children and young people (cyp)
So that I create a consistent experience across products_

## Links and resources

Relates to:
#413 

## Acceptance Criteria

* [ ] Add guidance to design system

**Comment by kelliedesigner** [comment]
Barnardo's ran a co-design workshop with cyp July 2018.

**First draft of guidance from the workshop:**

When requesting information from children and young people you should:
- explain why information is being requested
- explain who will see any personal information
- allow them to remain anonymous where possible
- avoid manipulative design patterns (dark patterns)

When writing for children and young people you should:
- use an informal positive tone
- be clear and concise
- be practical and actionable
- avoid difficult topics at the beginning of journeys
- avoid long paragraphs
- avoid being authoritarian, for example provide ‘tips’ not ‘rules’

When using photography of children and young people you should:
- match with the tone of the content
- include descriptive ‘alt tags’ in the code

When using footage of children and young people you should:
- include subtitles
- include a transcription
- avoid added music or a soundtrack

**Comment by jeddy3** [comment]
For another issue:

> When providing the ability for young people to speak to adults:
> - make it clear who the adults are that are involved in the conversation if applicable
> - provide information about the adult so it is someone they know rather than a stranger
> - avoid making assumptions about what young people want to talk about
> - avoid making young people repeat information
