### ISSUE TITLE
Fix indicator of progression on StartLink

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#298]
The StartLink requires further differentiated from the AttentionGrabbingLink and SubmitAction, to include a visual representation of progression.

<img width="826" alt="screen shot 2018-08-24 at 11 51 24" src="https://user-images.githubusercontent.com/6122118/44581153-80a38a80-a794-11e8-8db7-085d69504319.png">

**Comment by kelliedesigner** [comment]
Gov.uk
<img width="371" alt="screen shot 2018-08-24 at 11 55 12" src="https://user-images.githubusercontent.com/6122118/44581180-97e27800-a794-11e8-9aa6-299e30ebd69e.png">

RNLI
<img width="333" alt="screen shot 2018-08-24 at 11 56 35" src="https://user-images.githubusercontent.com/6122118/44581237-ce1ff780-a794-11e8-8b32-d14dc98f9506.png">

Save the Children
<img width="189" alt="screen shot 2018-08-24 at 11 57 52" src="https://user-images.githubusercontent.com/6122118/44581274-f7d91e80-a794-11e8-93d2-66384e1af566.png">

**Comment by jeddy3** [comment]
Done in https://github.com/barnardos/design-system/pull/305
