### ISSUE TITLE
Expand the colour palette to include tints and shades

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#31]
_As a user of the design system
I want tints and shades to be specified
So that I can quickly adopt them for my project_

## Description
The current iteration of the colour palette provides limited info on specific tints and shades of colours. This may create a more cumbersome process as other tools like Photoshop would be used to create shades in order to get hex codes, and inconsistencies may arise.

## Links and resources
https://govuk-elements.herokuapp.com/colour

## Acceptance criteria
- [x] Include tints
- [x] Include shades
- [x] Include common greys

**Comment by jeddy3** [comment]
Done in https://github.com/barnardos/design-system/pull/49
