### ISSUE TITLE
Expand the design principles

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#32]
_As a user of the design system
I would like more explanation of the design principles
So that I am clear on how to follow them_

## Description

Currently the design principles are four high level points.

@sl33p says: I would like to see an explanation of what those headline principles mean (down the line). Building this inside out makes sense, but at the same time it's difficult to review as the chronology is reversed. We get to see the outcome, and slowly the reasons for the decisions are revealed.

## Links and resources

https://www.gov.uk/guidance/government-design-principles
https://principles.design/

## Acceptance criteria

- [x] Flesh out design principles
- [x] Add principle about start small and iterating based on user testing and user needs
- [x] 'focus on functional considerations' = 'priortise functional considerations'

**Comment by olliewright** [comment]
Following 2 briefing sessions with Deeson, and the confusion that followed, this ticket is now a priority.

When addressing this ticket:

- Think about how different Barnardo's departments (eg. Marketing Dept / Lottery Dept) may share this information as part of the briefing and procurement process when choosing future web design agencies.

**Comment by kelliewellingtons** [comment]
The principles are to:
- start small and iterate based on user needs
- priortise functional considerations over aesthetics
- start with the most constrained environment
- only add complexity when justified
- Avoid print-based language and methodologies
- maintain consistency
- work in the open
