### ISSUE TITLE
Add submit button component

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#33]
_As a user of the design system
I want to see the convention for submit buttons
and be provided with a reusable component
So that my service can be consistent with all other Barnardo's digital services_

## Description

Now that the design system includes rules and guidance on styles such as layout, typography and colour, it now needs to be expanded to include the reusable components that use these styles. 

The benefit of sharing reusable components is that it maximises efficiencies in product teams, reduces debate and duplication, and maintains consistency across all products and services.

The submit button is a logical place to start as there are, despite seeming simple, so many usability and accessibility considerations. 

## Acceptance criteria

- [x] Add a section with for the submit button component to the design system
- [x] Addresses accessibility/usability considerations
- [x] Works on target devices and browsers

**Comment by jeddy3** [comment]
Following on from https://github.com/barnardos/design-system/issues/2#issuecomment-365987254...  the behaviour of the browser back button is different for links and buttons i.e. buttons display a "Resubmit the form warning?".

**Comment by jeddy3** [comment]
A key finding from [GDS](https://govuk-elements.herokuapp.com/buttons/):

> Use buttons to move though *a transaction*, aim to use *only one button per page*. [emphasis mine]

Key accessibility findings from [WebAim](https://webaim.org/techniques/hypertext/link_text):

> Avoid uninformative link phrases like "click here" and "read more"

> Browsers underline hypertext links by default. It is possible to remove the underline using Cascading Style Sheets (CSS), but this is a bad idea most of the time.

Key accessibility and usability findings from [Nathan Curtis](https://medium.com/eightshapes-llc/buttons-in-design-systems-eac3acf7e23):

> Limit One Per Page, Unless Repeating a Primary Action

> Beware of Ghosts in the Machine i.e. no-fill buttons

> Distinguish Buttons from Links

Lastly, [a summary article](https://medium.com/simple-human/but-sometimes-links-look-like-buttons-and-buttons-look-like-links-9b371c57b3d2) about distinguishing buttons from links.

**Comment by kelliewellingtons** [comment]
Key findings from [Buttons shouldn’t have a hand cursor](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)

> Links have always been handled this way since the web came along — this is the convention of the web that you need not innovate on. You can rest easy knowing that browsers have you covered. This leaves you and your team to solve real problems.

**Comment by kelliewellingtons** [comment]
Key findings from [But sometimes links look like buttons (and buttons look like links)](https://medium.com/simple-human/but-sometimes-links-look-like-buttons-and-buttons-look-like-links-9b371c57b3d2)

> Making a link look like a button is materially dishonest. It tells users that links and buttons are the same when they’re not.

> For example, we can open a link in a new tab, copy the address or bookmark it for later. All of which we can’t do with buttons.

> It’s wise to have only one primary link/action/button anyway. Admittedly this isn’t always possible, or even the right thing to do but we can explore this approach on a case by case basis.

> **How can we differentiate buttons and links that form part of the same menu?** 

> The problem here is that we want the items to be equally weighted without removing the affordance.

> One thing we definitely shouldn’t do is give the button an underline. This would be deceptive.

> Semantics are there for a reason, why design the meaning out of a component due to aesthetic minimalism?

**Comment by jeddy3** [comment]
From [Dyslexia Association of Ireland](http://www.dyslexia.ie/information/computers-and-technology/making-information-accessible-dyslexia-friendly-style-guide/)

> If you are producing information to be read by others, it is important to remember that up to 10% of your readers may have dyslexia.
> Use lower case letters. Avoid unnecessary use of capitals. Using all capital letters can make it harder to read

**Comment by kelliewellingtons** [comment]
From [Discussion in Gov](https://paper.dropbox.com/doc/Navigation-buttons-continue-next-previous-ghLqL5a9Ostxxb3rvBhyO)

> - avoid similar styles elsewhere on the page that could be confused for buttons
> - try to have as few buttons on a form as possible - just one is best
> - avoid excessively long button text
> - make sure the button text describes an action

**Comment by kelliewellingtons** [comment]
From [UX Matters](https://www.uxmatters.com/mt/archives/2012/05/7-basic-best-practices-for-buttons.php)
> Basic best practices for buttons:
1.  Make buttons look like buttons.      
2. Put buttons where users can find them.
3. Make the most important button look like it’s the most important one.
4. Put buttons in a sensible order.
5. Label buttons with what they do
6. If users don’t want to do something, don’t have a button for it.
7. Make it harder to find destructive buttons.

**Comment by kelliewellingtons** [comment]
Regarding content on buttons from [UX Booth](http://www.uxbooth.com/articles/the-grammar-of-interactivity/)
> Apply a generalized principle to chose a grammatically correct form of words

> It starts with a verb
> Buttons are for actions, like “Get a quote,” “Download,” “Open an account,” “Go to checkout.” The text on the button should begin with a verb. Otherwise it’s not a call-to-action, just a button with some text on it.
> “More information” for example, is not a call-to-action.

**Comment by kelliewellingtons** [comment]
Regarding flat forms and lack of affordance on [A List Apart](http://alistapart.com/article/flat-ui-and-forms)

> The three biggest ways flat forms fail
> The Klout example above nicely demonstrates the three largest ways in which flat UI forms often fail to deliver user-friendly experiences:

1. Lack of affordance (affordance is how much the design of an object—physical or digital—suggests use, like a chair inviting you to sit)
2. Insufficient distinction between form elements (e.g., fields versus labels versus instructions versus buttons)
3. Insufficient hierarchy within categories of form elements (e.g., primary versus secondary buttons)
