### ISSUE TITLE
Draft a blog post about design system

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#35]
## Description

This ticket is to draft up a blog post to add to the Barnardo's Digital blog.

## Links and resources

The Barnardo's digital blog: https://blog.barnar.do/

## Acceptance criteria
- [x] Put together a first draft of the intro to the DS post
- [x] Share draft with DM

**Comment by kelliewellingtons** [comment]
https://docs.google.com/document/d/10U7ZIDn_YsyvgL63wVZvNdakyR1i1dWB5U8DkPlmyuI/edit#

**Comment by kelliewellingtons** [comment]
@jeddy3 I'll hand this over to you to develop the draft further in this sprint.

**Comment by kelliedesigner** [comment]
Post is now drafted. We plan to have one last look tomorrow morning before sending it to DM for review and closing this ticket. Further iterations will be captured in a subsequent ticket.

**Comment by kelliedesigner** [comment]
@olliewright @sl33p 
We have completed the draft of this post, and it is now ready for your review:
https://docs.google.com/document/d/10U7ZIDn_YsyvgL63wVZvNdakyR1i1dWB5U8DkPlmyuI/edit#

**Comment by kelliedesigner** [comment]
This issue is now complete, and future issues can be created to makes changes.
