### ISSUE TITLE
Help DS consumers find corresponding desk research

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#36]
Each GDS component page, .e.g. buttons, has a link to Dropbox Paper where discussions, research and rationale are recommended.

We could do the same with a link to GitHub issues e.g. #33

# Acceptance criteria

- [ ] insert a link to the relevant gitHub issue on the design system pages
- [ ] each component should have at least one link (most likely)

**Comment by jeddy3** [comment]
Each GDS component page, .e.g. [buttons](http://govuk-elements.herokuapp.com/buttons/), has a link to Dropbox Paper where discussions, research and rationale are recommended.

We could do the same with a link to GitHub issues e.g. https://github.com/barnardos/design-system/issues/33

**Comment by sl33p** [comment]
sounds great
