### ISSUE TITLE
Remove barriers to contributing

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#38]
_As a user of the Design System,
I want to know how I can contribute
So that I can help improve it_

## Description

Contributing guidelines will help us define 

- How do I contribute?
-  What is the process of asking questions?
- What do I do if something I need is not there?

## Acceptance criteria
- [x] Meet Github Contributing criteria as described: https://github.com/barnardos/design-system/community

**Comment by jeddy3** [comment]
Six point criteria:
https://github.com/barnardos/design-system/community

Contributing guidelines
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

> For the repository owner, contribution guidelines are a way to communicate how people should contribute.
> For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.

Adding code of conduct:
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

>  A code of conduct (1) defines standards for how to engage in a community. (2) It signals an inclusive environment that respects all contributions. (3) It also outlines procedures for addressing problems between members of your project's community. 

Do we take the same approach as writing content for the design system itself i.e. begin by writing the smallest amount of copy to address these user needs?

**Comment by joelcarr** [comment]
We can take inspiration from https://github.com/alphagov/govuk-frontend/blob/master/CODE_OF_CONDUCT.md and https://github.com/alphagov/govuk-frontend/blob/master/CONTRIBUTING.md

**Comment by olliewright** [comment]
Following 2 briefing sessions with Deeson, and the confusion that followed, this ticket is now a priority.

When addressing this ticket:

- Think about how different Barnardo's departments (eg. Marketing Dept / Lottery Dept) may share this information as part of the briefing and procurement process when choosing future web design agencies.
