### ISSUE TITLE
Fix the emphasis of the three layout and typographic rules 

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#39]
While chatting with the Creative Team it became clear that there needs to be a better separation between the _rules that should be followed_ and the _suggested implementation_ of those rules. Currently, the rules aren't emphasised and their importance isn't clear.

Additionally, perhaps moving the example directly below the rules is more valuable as it can become just an example of the three rules rather than the current _mix_ of rules and suggestions? e.g.

![artboard](https://user-images.githubusercontent.com/808227/36728518-e9eb948c-1bb8-11e8-99e6-fc84b9a06995.png)

This shows all three rules in effect: the 8px spacing, 4px line height and the 1.125 type scale.

**Comment by kelliewellingtons** [comment]
Agree let's look at how we can emphasise and differentiate the rules
