### ISSUE TITLE
Add how to display images

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#396]
_As a user of the Design System
I want to know how to display images
So that there is consistency across products_

## Description 

- Decide on one or more set aspect ratios, and appropriate use of them.

## Acceptance Criteria

- [ ] Add how to display images to the Design System

**Comment by kelliedesigner** [comment]
Current website:
<img width="1205" alt="screen shot 2018-10-31 at 09 27 22" src="https://user-images.githubusercontent.com/6122118/47778703-553aa000-dcef-11e8-99e1-4ff71004d7b3.png">

<img width="1280" alt="screen shot 2018-10-31 at 09 27 38" src="https://user-images.githubusercontent.com/6122118/47778718-5c61ae00-dcef-11e8-8032-729b46478394.png">

<img width="1129" alt="screen shot 2018-10-31 at 09 28 05" src="https://user-images.githubusercontent.com/6122118/47778724-61bef880-dcef-11e8-99ae-5f21425d068e.png">

**Comment by kelliedesigner** [comment]
Guidance draft

**Images**
- Only use images if there’s a real need and avoid unnecessary decoration
- The aspect ratio for images should be 3:2
- All images must have an alt text
- include a description of the image in the code to help those who are unable to see it

**Comment by jeddy3** [comment]
From [Designing An Aspect Ratio Unit For CSS](https://www.smashingmagazine.com/2019/03/aspect-ratio-unit-css/):

> The CSS Working Group have designed an aspect ratio unit for CSS. While this isn’t in browsers yet, this article takes a look at the process of designing a new sizing method and explains how it will work.
