### ISSUE TITLE
Fix lack of emphasise that service users can be children

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#40]
Jason highlighted that this is an exciting opportunity to create a design system that meets the needs of service users _who are children_. There's an opportunity to become the canon for this. 

How can we capture this within the design system so it becomes a guiding principle?

Could a start be a simple text change? From:

> Helping digital product teams create a consistent user experience and maximise efficiency.

to something like:

Helping digital teams maximise their efficiency in creating a consistent experience for Barnardo's service users, including children.

**Comment by kelliewellingtons** [comment]
This sounds like a valuable change to make, let's go with the copy above and get this bug resolved.
