### ISSUE TITLE
Investigate optimum typeface for children and young people. Compare Proxima Nova to others

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#41]
There is a need for the future of the Barnardo's brand to consider the typeface choice as part of:
- the brand personality and look-and-feel
- maximising readability and engagement of users

Extensive research exists on the best typefaces for engaging children and young people.

This issue is to research what considerations to make when choosing the typeface, and look at potential typeface options.

Related to: https://github.com/barnardos/design-system/issues/40

**Comment by kelliewellingtons** [comment]
Key findings from [fonts.com](https://www.fonts.com/content/learning/fyti/situational-typography/typography-for-children)

When selecting a typeface for a children’s text, choose:

> - warm, friendly design with simple, generous letter shapes
> - rounded and open counters
> - typefaces with larger x-heights
> - one-story ‘a’s and ‘g’s 
> - book or medium weight; stay away from hairline or very bold weights
> - standard width, don’t use condensed or expanded typefaces
> - italics that are easy-to-read, and not overly condensed or stylised

**Comment by kelliewellingtons** [comment]
Key findings from [Research into Typographic Design](https://issuu.com/anna_magombe/docs/research_into_typographic_design_for_young_people_) by Anna Magombe

Best fonts for readability for children:
![screen shot 2018-03-10 at 20 11 28](https://user-images.githubusercontent.com/6122118/37246347-a93bbf8a-249f-11e8-929e-9a5ba0ee4d2e.png)

**Comment by kelliewellingtons** [comment]
Google font review – typefaces with a primary-school-style lowercase ‘a’

List of webfonts with single storey characters:
https://tallhat.com/2016/04/google-fonts-with-primary-school-style-lowercase-a/

**Comment by kelliewellingtons** [comment]
Aim
To provide more personality of the Barnardo's brand through font choice, while maintaining high accessibility and readability standards.

![proxima-nova-fs-albert](https://user-images.githubusercontent.com/6122118/37246876-9c7a3e02-24a9-11e8-8e17-a9982563fcec.png)

**Comment by kelliewellingtons** [comment]
Key findings from [Effective Use of Typography in Applications for Children] Designing for Children
Early engagement in the digital world (https://www.uxmatters.com/mt/archives/2011/06/effective-use-of-typography-in-applications-for-children-3.php)

**Comment by kelliewellingtons** [comment]
Webfonts with single storey characters:
https://www.fontfont.com/fonts/schulbuch
http://www.sassoonfont.co.uk/
https://www.fontsmith.com/fonts/fs-albert

**Comment by kelliewellingtons** [comment]
**FS Albert**

![screen shot 2018-03-16 at 12 10 23](https://user-images.githubusercontent.com/6122118/37519973-28dee9de-2913-11e8-8bc4-eaeaa16371b6.png)

**Comment by kelliewellingtons** [comment]
Comparison between Proxima Nova, and FS Albert (including paragraph text):

![37247048-fffccb7c-24ac-11e8-8cdf-acf62c7900d7](https://user-images.githubusercontent.com/6122118/37520004-4b6792ee-2913-11e8-89a2-49bc3a3d9088.png)

![37519581-85b4d134-2911-11e8-840a-c80c3a24758f](https://user-images.githubusercontent.com/6122118/37520013-54740476-2913-11e8-8143-6fed2add5a1a.png)

Mock up of FS Albert in a transactional service:

![37247246-299f8f84-24b0-11e8-91a1-4bce7f872d59](https://user-images.githubusercontent.com/6122118/37520019-58cf627c-2913-11e8-812a-1eb4a084b631.png)

**Comment by sl33p** [comment]
what's the status of this?

**Comment by kelliewellingtons** [comment]
**Feedback from today's meeting**

Ensure that we test and validate this typeface with a cross-section of users:
- Children and young people
- Teens (eg leaving care)
- Project workers
- Staff
- Doners
- Researchers

**Comment by kelliewellingtons** [comment]
**Next steps**

- Mockup designs with chosen typeface for testing
- Test with users

**Comment by kelliewellingtons** [comment]
Continued in #95

**Comment by jeddy3** [comment]
Nunito - open source and meets the above criteria except single-story a:
https://fonts.google.com/specimen/Nunito

Available in light and semi. Only 16k per weight.

**Comment by kelliedesigner** [comment]
[Heinemann](https://www.myfonts.com/fonts/fw-heinemann/heinemann)
