### ISSUE TITLE
Update typeface using open source fonts

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#414]
- Proxima Nova was a temporary choice
- It was chosen as it has a single-storey 'a'.
- Proxima Nova is licensed
- This is unsustainable at scale, teams building products for Barnardo's are currently using Verdana or other methods which are not desirable and not maintaining consistency.
- There are other open source typefaces exist which have a single storey 'a'.
- If we go with Google Suite internally, using a Google font will ensure consistency in print and presentation materials
- There is a brand audit in progress
- The outcome may result in the font may changing
- We would like to avoid spending more money on licensing for a font that is temporary and may change
- Additionally, there is a hypothesis that Proxima Nova is generic and does not provide the personality necessary to compliment the Barnardo's brand.

The aim of this work is to:
- save money
- improve ease of teams implementing a typeface
- improve consistency in the short term while the audit continues
- improve the look and feel of the brand

* this is not necessarily the final choice, it is an iteration to move in the right direction.

## Links and resources

References: 
> - #3 Apply consistent typography
> - #15 Experiment with typefaces on DTW
> - #41 Investigate optimum typeface for children and young people 
> - https://tallhat.com/2016/04/google-fonts-with-primary-school-style-lowercase-a/
> - https://bdatech.org/what-technology/typefaces-for-dyslexia/
> - https://medium.muz.li/30-free-and-open-source-typefaces-released-recently-best-collections-5b46f9d89f65

## Acceptance Criteria

- [x] Create a page which visually displays options of typefaces to replace Proxima Nova
- [ ] Create relevant follow-up tickets

**Comment by kelliedesigner** [comment]
https://fonts.google.com/specimen/Nunito

**Comment by kelliedesigner** [comment]
3. Rubik
<img width="385" alt="screen shot 2018-11-20 at 16 34 13" src="https://user-images.githubusercontent.com/6122118/48788180-2efe9380-ece2-11e8-9bc3-2e1f6455d277.png">

**Comment by tosbourn** [comment]
Can I ask that one criteria we use when spiking fonts be we print a test page from a website and see how well the font looks when printed.

People print content off the web all the time, and any font we choose should play nice with printers.

**Comment by kelliedesigner** [comment]
> Can I ask that one criteria we use when spiking fonts be we print a test page from a website and see how well the font looks when printed.
> 
> People print content off the web all the time, and any font we choose should play nice with printers.

I have added this to the Acceptance criteria.

**Comment by jeddy3** [comment]
After an initial investigation, none of the open source fonts were viable candidates. As such, we're going to investigate what can be done to improve the consumption of the Proxima Nova font. See https://github.com/barnardos/design-system/issues/424

**Comment by jeddy3** [comment]
> investigate what can be done to improve the consumption of the Proxima Nova font

Following up with more information to weigh up the pros and cons...

**The good:**

> This is unsustainable at scale,

Adobe Fonts has taken over Typekit. They seem to have a far more liberal approach to licensing. For example, gone are the:

- monthly limits
- manually maintaining a whitelist of domains

This makes it easier for teams to implement the typeface

See: https://helpx.adobe.com/fonts/using/introducing-adobe-fonts.html#KitsarenowWebProjects

> If we go with Google Suite internally

Proxima Nova seems to be available in the Google Suite.

> We would like to avoid spending more money on licensing for a font

It's a fixed monthly fee regardless of the number of domains/products, and that fee isn't prohibitively expensive.

**The not-so-good:**

> It was chosen as it has a single-storey 'a'.

It's the "alternative" version comes with a single-storey 'a', but the licensing (and consumption) around this version isn't clear.

> We would like to avoid spending more money on licensing for a font

There's still a monthly fee.

---

There are still important questions around the suitable of the font from a brand and CYP reading experience perspective but some of the barriers to teams consuming the typeface and costs aren't as tall as initially thought.
