### ISSUE TITLE
Evaluate Submit component is on brand

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#42]
We have created a button component in the Design System #33 

This complies with accessibility and best practice

This ticket is to discuss with the team whether this component is on brand with where we want to take the Barnardo's visual language.

Examples of other charities and how they have included their visual language into their Action components are below:

![image uploaded from ios](https://user-images.githubusercontent.com/6122118/36852139-e86d1ddc-1d62-11e8-825c-7d1ad2867c25.png)
![image uploaded from ios 1](https://user-images.githubusercontent.com/6122118/36852157-ef46af74-1d62-11e8-9cf9-6ec63e2c0eaa.png)

**Comment by jeddy3** [comment]
From [Nathan Curtis](https://medium.com/eightshapes-llc/buttons-in-design-systems-eac3acf7e23):

> The Primary Button
> 1. Set a System’s Stylistic Tone
> A button is the purest atomic expression of a system’s visual style. It combines the “big three” attributes— color, typography, and iconography — into a non-splittable atomic part. Buttons also provoke discussion of space: padding inside (particularly, to a label’s left and right) and margin outside (adjacent to other elements). Ultimately, button can even surface more esoteric attributes like roundedness (via border-radius) and lift (via box-shadow).

**Comment by kelliedesigner** [comment]
I deem this issue to no longer be relevant, as the visual language has been stabilised, and can always be iterated on in future when appropriate.
