### ISSUE TITLE
Add performance budget guidance

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#451]
_As a consumer of the design system
I want guidance on performance budgets
So that I can ensure my product is fast and consistent with other products_

## Description

Possible metrics:

First Contentful Paint - under 2s
First Meaningful Paint - under 2s
Time to Interactive - under 3s

## Links and resources

- https://developers.google.com/web/fundamentals/performance/why-performance-matters/
- https://medium.com/@addyosmani/the-cost-of-javascript-in-2018-7d8950fbb5d4

## Acceptance Criteria

- [x] Add guidance

**Comment by olliewright** [comment]
Great article!

**Comment by jeddy3** [comment]
> [Who has the fastest website in F1?](https://jakearchibald.com/2019/f1-perf/)

> It's great to see HTTPS, HTTP/2, gzip, minification, and decent caching widely used. These are things folks in the performance community have been pushing for a long time, and it seems like it's paid off.

**Comment by jeddy3** [comment]
[Performance budgets that stick](https://timkadlec.com/remembers/2019-03-07-performance-budgets-that-stick/):

> To be effective, a performance budget has to be concrete, meaningful, integrated, and enforced.
