### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#454]
_As a regular consumer looking for something specific
I want to search for it
So that I can jump directly to it without having to navigate through the DS_

## Description

> Users love search for two reasons:
> - Search lets users control their own destiny and assert independence from websites' attempt to direct how they use the web. Testing situations routinely validate this. A typical comment is: "I don't want to have to navigate this site the way they want me to. I just want to find the thing I'm looking for." This is why many users go straight to the homepage search function.
> - Search is also users' escape hatch when they are stuck in navigation. When they can't find a reasonable place to go next, they often turn to the site's search function. This is why you should make search available from every page on the site; you cannot predict where users will be when they decide they are lost.

## Links and resources

- https://community.algolia.com/docsearch/apply.html
- https://www.nngroup.com/articles/search-visible-and-simple/

## Acceptance Criteria

- [ ] Add Search

**Comment by kelliedesigner** [comment]
@jeddy3 
Include fix height of Search component:
Make the height the same as  Text Input on small viewports
Add media query to reduce height on large viewports
