### ISSUE TITLE
Create link component

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#47]
_As a user of the Design System
I want to be able to access a component for linking to resources
So that I can make my service consistent with others_

## Description

Linking to resources is a fundamental aspect of interfaces. There needs to be a component that can be applied to other components and elements to make them links.

## Links and resources

- Builds on the findings in #33 

The key findings from [WebAim](https://webaim.org/techniques/hypertext/link_text#appearance):

> - Links should look like links, and nothing else should.
> - Browsers underline hypertext links by default. It is possible to remove the underline using Cascading Style Sheets (CSS)

## Acceptance criteria

- [x] Add component to design system
- [x] Addresses accessibility/usability considerations
- [x] Works on target devices and browsers

**Comment by kelliewellingtons** [comment]
Key findings from [Buttons shouldn’t have a hand cursor](https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b)

> Links have always been handled this way since the web came along — this is the convention of the web that you need not innovate on.

> You can rest easy knowing that browsers have you covered. This leaves you and your team to solve real problems.

**Comment by kelliedesigner** [comment]
Key findings from [NN Group](https://www.nngroup.com/articles/guidelines-for-visualizing-links/):
> * don't use bold-facing as a hover effect, because making the font wider may cause the text to re-align.

**Comment by kelliedesigner** [comment]
Key findings from [UX Booth](https://www.uxbooth.com/articles/is-the-underlined-link-hurting-readability/):
> * Don’t underline text that isn’t a link
> * Use different colors for visited and unvisited links
> * Make links accessible by writing semantic HTML
> * Write specific messages for your links, that indicate where the user will be directed (avoid uninformative phrases such as ‘click here’)
> * Keep linked phrases short, 3-5 words
> * Maintain overall style consistency and integrity across the site
> * Don’t put more than 100 links on any one page

**Comment by kelliedesigner** [comment]
Key findings from [Prototypr](https://blog.prototypr.io/a-guide-to-designing-perfect-links-in-ux-414558f35730):
> * Provide visual cue to suggest clickability for all types of links.
> * Distinguish the visited and unvisited for navigation links
