### ISSUE TITLE
Add how to display a download link

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#476]
_As a consumer
I want to know how best to display a download link
So that I can make my product consistent with others_

## Description

- Document name (use a meaningful phrase that makes sense out of context)
- File format
- Option for multiple formats or versions (ie Large print or accessible version)
- File size (important for accessibility/latency)

## Acceptance Criteria

- [x] Add component
- [x] Cross-browser tests
- [x] Accessibility tests

**Comment by kelliedesigner** [comment]
New look and feel:
<img width="175" alt="screen shot 2019-02-22 at 12 13 29" src="https://user-images.githubusercontent.com/6122118/53241986-52e3c380-369b-11e9-8b79-ec18dfb43ce9.png">

**Comment by kelliedesigner** [comment]
Gov.uk

<img width="633" alt="screen shot 2019-02-27 at 12 54 45" src="https://user-images.githubusercontent.com/6122118/53491680-e7309a80-3a8e-11e9-8a66-352529fe90a8.png">

<img width="654" alt="screen shot 2019-02-27 at 12 51 26" src="https://user-images.githubusercontent.com/6122118/53491689-eac42180-3a8e-11e9-91df-58fc290638d3.png">

<img width="647" alt="screen shot 2019-02-27 at 12 53 14" src="https://user-images.githubusercontent.com/6122118/53491693-ed267b80-3a8e-11e9-9b5d-7cdc68e2e258.png">

<img width="615" alt="screen shot 2019-02-27 at 12 53 57" src="https://user-images.githubusercontent.com/6122118/53491700-f0216c00-3a8e-11e9-9d5c-4e390ec21494.png">

<img width="620" alt="screen shot 2019-02-27 at 12 54 31" src="https://user-images.githubusercontent.com/6122118/53491702-f283c600-3a8e-11e9-8d20-6ba118af0a79.png">

**Comment by kelliedesigner** [comment]
Nhs.uk

<img width="576" alt="screen shot 2019-02-27 at 13 02 11" src="https://user-images.githubusercontent.com/6122118/53492119-f82ddb80-3a8f-11e9-829f-0766c62b3758.png">

**Comment by kelliedesigner** [comment]
Co-op

<img width="638" alt="screen shot 2019-02-27 at 13 03 16" src="https://user-images.githubusercontent.com/6122118/53492164-1693d700-3a90-11e9-8bee-224e1a780b85.png">

**Comment by jeddy3** [comment]
Findings from [digital NZ gov](https://www.digital.govt.nz/standards-and-guidance/design-and-ux/usability/linking-to-non-html-files/):

> A link to a non-HTML document should provide information about the document, including a meaningful name, the file format and the file size. This gives users a good idea of what to expect if they click on the link.

**Comment by jeddy3** [comment]
Findings from [Webaim]()

> A link to a PowerPoint slide show, for example, could say "Third quarter sales projections (PowerPoint)" or something similar, and a link to a PDF file could say "Tax form 1040 (PDF)" or something similar.

> When identifying the link file type, this additional content should be presented inside the link, rather than just after it, so that the information is presented with the link if a screen reader users navigates by links or reads a link list.

**Comment by jeddy3** [comment]
Findings from [accessabilly](https://accessabilly.com/proposal-for-a-more-accessible-download-link/):

> - Semantically, the download is always a Hyperlink (<a/>), never a <button>.
> - Provide media type visually readable
> - Provide file size visually readable
> - Use icons & color to enhance visual presence
> - Open the download link in the same window
> - Semantical enhancement with HTML5
