### ISSUE TITLE
Add ability to navigate sideways

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#491]
_As a consumer
I want to navigate from one bit of related content to another
So that it's easier for me_

## Description

We should provide a means for consumers to continue their journey onto related content.

## Acceptance Criteria

- [ ] Add Pagination or Promos to the bottom of each page

**Comment by kelliedesigner** [comment]
Key findings from [Paging buttons position – Top, Bottom or both?](https://ux.stackexchange.com/questions/31603/paging-buttons-position-top-bottom-or-both) 

> - The question is on where to place the paging buttons on a catalog page. We have some basic choices here.
> - Only on bottom.
> - Both on bottom and on the top.
> - The obvious argument to place it only on the bottom of the page is to force your user to see your entire catalog first
> - The argument to place it also on the top of the catalog page is to help the user, after is scroll down, to scroll again up, see second time some line that have keep in mine, and then move to the next page with out the need to scroll again down.
> - The question is – its better for the user to have it on both places or not. Maybe some sites need to force the user to scroll down and up again and that’s their goal, to see as much as possible, but it is good for a user or make him leave the site is you make him frustrate by up and down
> - One alternative that I have think about is to have the upper paging buttons hidden, when the user is scroll down you make it visible, and if the user come up again its shown, that way you force your user to see the entire catalog first before move to the next page, but keep it on both.
