### ISSUE TITLE
Add how to emphasise an area of content (e.g. panel)

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#500]
_As a consumer
I want to know how best to panel up content
So that I can make my product consistent with others_

## Description

Sometimes visually panelling content up helps the user consume content.

## Acceptance Criteria

- [ ] Add component
- [ ] Cross-browser tests
- [ ] Accessibility tests

**Comment by kelliedesigner** [comment]
<img width="1298" alt="screen shot 2019-02-25 at 11 23 32" src="https://user-images.githubusercontent.com/6122118/53334197-f88f7080-38ef-11e9-9da3-6bd8a3f86715.png">

**Comment by kelliedesigner** [comment]
<img width="448" alt="screen shot 2019-02-25 at 11 25 13" src="https://user-images.githubusercontent.com/6122118/53334236-12c94e80-38f0-11e9-9652-686415ec4873.png">
