### ISSUE TITLE
Add how to progressively reveal content

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#534]
_As a user of the Design System,
I want to know how to provide content which can be revealed
So that there is consistency across products_

## Acceptance Criteria

- [ ] Research usability and accessibility of progressively revealing content
- [ ] Add guidance into the Design System

**Comment by kelliedesigner** [comment]
**Register to vote**

<img width="609" alt="screen shot 2019-01-23 at 12 01 03" src="https://user-images.githubusercontent.com/6122118/51605308-9addc200-1f06-11e9-9da1-cf335cc36f63.png">

**Comment by kelliedesigner** [comment]
**Mozilla Developer Network**

<img width="198" alt="screen shot 2019-01-23 at 12 02 45" src="https://user-images.githubusercontent.com/6122118/51605368-d5475f00-1f06-11e9-8f5f-b45529a16212.png">

**Comment by kelliedesigner** [comment]
Key findings from [NN Group: Progressive Disclosure](https://www.nngroup.com/articles/progressive-disclosure/)

> - Progressive disclosure defers advanced or rarely used features to a secondary screen, making applications easier to learn and less error-prone.
> - Disclose everything that users frequently need up front
> - It must be obvious how users progress from the primary to the secondary disclosure levels
> - make the mechanics of this operation simple
> - label the button or link in a way that sets clear expectations for what users will find when they progress to the next level (strong information scent)

**Comment by kelliedesigner** [comment]
Key findings from [GOV.UK Github issue on Details](https://github.com/alphagov/govuk-design-system-backlog/issues/44)

> - From an accessibility point of view, they are not treated as links by screen readers assistive technology so the experience is totally different.

> - Native details can't be forced to display its contents when printed (unless element is already open on page load or was opened by user). This is because the visibility of the contents is toggled with open attribute in the markup, and this can't be controlled with CSS print styles.

**Comment by kelliedesigner** [comment]
Key findings on use of models:

[10 guidelines to consider when using overlays / modals](http://www.uxforthemasses.com/overlays/)

**Comment by olimj** [comment]
> > * [MDN (Mozilla Developer Network) web docs - The Details disclosure element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)
> 
> The 'details' element provides a good user experience with minimal html and can be styled.
> 
> 'Summary' can be included for the link text.
> 
> <img alt="screen shot 2019-03-07 at 06 59 32" width="717" src="https://user-images.githubusercontent.com/6122118/53937968-9b8d7a80-40a6-11e9-9f5c-966fa07b6b7b.png">
> 
> Working example, click 'System requirements' below.
> 
> System Requirements

Other Mozilla example doesn't seem to use a pointer cursor: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by olimj** [comment]
### Cursors on the details element

HTML example doesn't use a pointer cursor either: https://html.com/tags/details/

- Without any CSS, the cursor seems to use the text cursor on the details element.
- Considering this element is interactive, the text cursor doesn't 'feel' right.
- Could we use a default or pointer cursor to indicate an interaction?
-
