### ISSUE TITLE
Fix homepage components anchor links

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#550]
## Description

When using VoiceOver on iOS, clicking on one of the links within a promo in components (for example 'Choices' within 'Forms', takes you to the correct page, but does not jump down to the chosen section.

<img width="400" alt="screen shot 2019-01-28 at 12 51 17" src="https://user-images.githubusercontent.com/6122118/51754951-76741800-20b5-11e9-8145-709427d677e8.jpg">

References #522

**Comment by nickcolley** [comment]
Looks like this could be a bug with VoiceOver on iOS...

https://axesslab.com/skip-links/

If it is the same issue, this is the bug report to Apple: https://bugs.webkit.org/show_bug.cgi?id=179011

**Comment by jeddy3** [comment]
Thanks for the info Nick!

We'll close this issue for now.
