### ISSUE TITLE
Create short URL

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#57]
e.g. http://design-system.barnardos.org.uk

**Comment by sl33p** [comment]
I still think we need a name for the design system like all the cool kids have. Here are five suggestions:

1. Beistegui (after the count of Monte Cristo)
2. Kemptown (after the rural area in Nova Scotia)
3. Bad Sobernheim (after the German spa town)
4. Burutay Subaşı (after the Turkish volleyball player)
5. or Random Article (after the link on wikipedia where I got these name suggestions)

**Comment by jeddy3** [comment]
- [ ] Create short URL

**Comment by jeddy3** [comment]
@sl33p Does the team have a preferred way of creating shortened URLs?

**Comment by ritapatel7** [comment]
It would be good to have consistency for URLs for our projects, i.e. Digital Transformation is using barnardos- at the beginning, Design System is using .barnardos at the end like consent form. Is it possible to make them follow the same pattern i.e either have barnardos at the beginning or end of the project name.

**Comment by sl33p** [comment]
I've set up barnar.do/design-system but it will take a while to propagate. Will close this issue when we can see it live
