### ISSUE TITLE
Fix showing Layout, Site and Main

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#583]
`Layout` and `Site`, `Main` are consumable, but we haven't documented them yet in the Design System.

**Comment by kelliedesigner** [comment]
[Alphabetical Sorting Must (Mostly) Die](https://www.nngroup.com/articles/alphabetical-sorting-must-mostly-die/)
> - Summary: Ordinal sequences, logical structuring, time lines, or prioritization by importance or frequency are usually better than A-Z listings for presenting options to users.
