### ISSUE TITLE
[0.25 day] Investigate adding other template formats

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#633]
The design system exports react components, which reference CSS files. This means the CSS can be used by all platforms, but the templates can only be consumed in React projects.

This spike is to investigate the feasibility of exporting other templates languages from within the design system e.g. Twig and Erb

**Comment by jeddy3** [comment]
It was decided to not include twig or erb templates because:

1. the needs of Drupal make it difficult to consume BEM based components
2. there isn't a node based erb render, meaning we'd have to introduce a ruby dependency

**Comment by jeddy3** [comment]
It was decided to not include twig or erb templates because:

1. the needs of Drupal make it difficult to consume BEM based components
2. there isn't a node based erb render, meaning we'd have to introduce a ruby dependency
