### ISSUE TITLE
Fix Block Quote look and feel

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#635]
The Block Quote look and feel needs to be updated to align with the developing Barnardo's look and feel.

- Quote text and role should be in brand Black

<img width="366" alt="screen shot 2019-02-22 at 12 14 12" src="https://user-images.githubusercontent.com/6122118/53242031-7e66ae00-369b-11e9-9833-31f6949dcd24.png">

**Comment by kelliedesigner** [comment]
@olimj I've kept the role as regular weight instead of bold, the reason is because if we make the role bold, there will be no differentiation between name and role in the Prominent Block Quote. 

<img width="484" alt="screen shot 2019-02-22 at 15 38 11" src="https://user-images.githubusercontent.com/6122118/53253019-2e4a1480-36b8-11e9-9fc0-c9b2f2abad97.png">

Happy to chat about this.

**Comment by olimj** [comment]
Hey Kellie - cheers for that. Great point! I've only just been supplied
with the Proxima Nova font family so that's been fixed in the design now :)
https://docs.google.com/presentation/d/1Brvs-hosdrSYI8sXfciKeUeDXUPk6AesMP9qeBXeV4s/edit?usp=sharing
