### ISSUE TITLE
Add how to interact with young people in real time

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#637]
_As a user of the Design System,
I want to know how to interact with young people in real time
So there is consistency across products._

## Acceptance criteria
- [ ] Add guidance to the Design System

**Comment by kelliedesigner** [comment]
_**Barnardo's research on this topic**_

**Adults interacting with young people online**
Help young people feel comfortable and at ease sharing information when interacting with Barnardo’s staff online.

**When to use this pattern?**
This guidance should be used whenever young people interact with Barnardo’s staff online.
How it works

**Building Trust**
For young people to build trust with the person they’re speaking with online they need to know some background information about them. 

 Background information should include: 
- photo
- their age and gender 
- their role 
- their area of expertise 
- the team they work in

**Seeking Help and Support**
Young people should be provided with clear and relevant signposts to services who can help them. They should also be aware that these services are recommended by Barnardo’s

**Sharing Information**
When asking young people for their personal details be clear about how this information will be used and how it will help Barnardo’s support them.

**Tone of Voice**
When talking with young people online be calm, helpful and positive.

**Personalisation**
When getting online support young people should feel unique and not part of a system.

To encourage engagement allow young people to personalise content 

**Manage expectations**
Set expectations about response times for online chat and comments early with young people and give them alternative options in case they need immediate support

**Safeguarding**
Any online interaction or conversation with a young person should be recorded and logged for later retrieval by Barnardo’s staff and the young person.
