### ISSUE TITLE
Importing Page results in a compilation error

### ISSUE THREAD

**Issue by tosbourn** [barnardos/design-system#644]
## Description

When consuming the Design System in an external Gatsby project and using the `Page` component a compilation error is thrown.

## Step to reproduce

1. set up a Gatsby project
2. install DS NPM package
3. import `Page` component into a page
4. see the compilation error

## Code Samples

The page throwing the error:

```
import Helmet from "react-helmet";
import React from "react";
import {
  Page,
  Title,
  Paragraph,
  ListItem,
  BulletedList
} from "@barnardos/components";

const Index = () => {
  return (
    <Page>
      <Helmet>
        <title>{`Barnardo's Playbook`}</title>
      </Helmet>
      <Title>{`Barnardo's Playbook`}</Title>
      <Paragraph>{`This Playbook outlines how we work in Barnardo's Digital:`}</Paragraph>
      <BulletedList>
        <ListItem>{`test 1`}</ListItem>
        <ListItem>{`TEST 2`}</ListItem>
      </BulletedList>
    </Page>
  );
};
export default Index;
```

The error:

```
./node_modules/@barnardos/components/src/components/Site/index.js 10:2
Module parse failed: Unexpected token (10:2)
You may need an appropriate loader to handle this file type.
| 
| const Site = ({ children }) => (
>   <div className="Site">
|     <Helmet titleTemplate="%s - Barnardo's">
|       <html lang="en" />
```

For full code context visit the branch attached to [this page](https://github.com/barnardos/playbook/blob/ds-npm-spike/src/pages/index.js).

## Package details

```
├── @barnardos/components@0.1.0
├── @barnardos/eslint-config-barnardos@0.1.0
├── @barnardos/stylelint-config-barnardos@0.3.8
├── eslint@5.12.1
├── gatsby@2.0.95
├── gatsby-plugin-postcss@2.0.2
├── gatsby-source-filesystem@2.0.23
├── gatsby-transformer-json@2.1.7
├── npm-run-all@4.1.5
├── postcss-browser-reporter@0.5.0
├── postcss-import@12.0.1
├── postcss-preset-env@6.5.0
├── postcss-reporter@6.0.1
├── prettier@1.15.3
├── react@16.7.0
├── react-dom@16.7.0
├── react-helmet@5.2.0
├── slug@0.9.3
└── stylelint@9.10.1
```

**Comment by jeddy3** [comment]
> The error:

I'm not sure why this is failing now when it previously worked... 

It looks like we need to get Gatsby to compile our ES6-based components:

```js
// gatsby-config.js
module.exports = {
  plugins: [
    `gatsby-plugin-postcss`,
    {
      resolve: `gatsby-plugin-compile-es6-packages`,
      options: {
        modules: [`@barnardos/components`]
      }
    }
  ]
};
```

> using the `Page` component a compilation error is thrown.

The `Page` component isn't exported in the Design System package yet. So, you'll see another error related to that once the error above is fixed. We didn't include `Page` because some product-specific stuff needs to be set via the props of the components within it e.g. `description` on `Site`. We'll have a think about what's the best consumer experience here. In the meantime, you can create your own `Page` component:

```jsx
// components/Page/index.js
import PropTypes from "prop-types";
import React from "react";
import { Footer, Header, Layout, SkipLink, Site } from "@barnardos/components";

const Page = ({ children }) => (
  <Site description="<Your product description>">
    <Layout>
      <SkipLink />
      <Header title="Go to the <your product name> homepage" />
      {children}
      <Footer />
    </Layout>
  </Site>
);

Page.propTypes = {
  children: PropTypes.any
};

export default Page;
```

---

We've plans to create a prototype toolkit soon, which will make it easier to get going with the components.

**Comment by tosbourn** [comment]
Thanks @jeddy3 I will give that a go and report back.

**Comment by kelliedesigner** [comment]
@tosbourn Do you have an update on this issue?

Also this new guidance may be useful as reference: https://design-system.barnardos.org.uk/components/structure/

**Comment by tosbourn** [comment]
@kelliedesigner yup!

I followed @jeddy3's guidance and everything worked. Given that there is a prototype toolkit in the works I don't think any more action need to happen on this ticket.
