### ISSUE TITLE
[0.25 day] Investigate form component compatibility with formik

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#647]
[Formik](https://jaredpalmer.com/formik/) looks like an excellent React Form library. 

This spike is to investigate if the form components are compatible with it.

**Comment by joelcarr** [comment]
I created a new branch called [`formik-example`](https://github.com/barnardos/design-system/tree/formik-example) which explores how the current form components work within a form example (with and without Formik).

The current form components are not compatible for [React forms](https://reactjs.org/docs/forms.html). We require additional props such as `onChange` and `value`.

You can explore the [commits in my branch](https://github.com/barnardos/design-system/compare/formik-example) to see the changes required.

Shall we create issues to add these props required on form elements?

**Comment by jeddy3** [comment]
> Shall we create issues to add these props required on form elements?

Yes, please. A single "Fix form components compatibility with formik" issue with a checklist of components in would be great.

**Comment by joelcarr** [comment]
Created #732 to make our form components compatible for Formik.
