### ISSUE TITLE
Add how to gather multiple pieces of data 

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#67]
_As a user of the design system
I want to know how to gather multiple pieces of data from a user
So that there is a consistent experience across services_

## Description

Submitting data is a fundamental aspect of interfaces.  Often multiple pieces of data are gathered at one time. There are a number of problems surrounding this:

![multiple](https://user-images.githubusercontent.com/808227/37207199-d3fe30fc-2393-11e8-9fab-1d85e9685b55.jpg)

## Links and resources

- Desk research findings from #65 

- https://www.gov.uk/service-manual/design/form-structure
- https://paper.dropbox.com/doc/Progressive-disclosure-rUra4ZisgaWjafhBP1ivr
- https://www.gov.uk/service-manual/design/progress-indicators
- https://webaim.org/techniques/forms/
- http://coop-design-manual.herokuapp.com/styles/forms/index.html
- https://www.nvaccess.org/donate/
- https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/How_to_structure_an_HTML_form
- https://webaim.org/techniques/forms/

## Acceptance Criteria

Document solutions to following concerns:

- [x] Consistent style/spacing
- [x] Focus attention
- [x] Logical grouping
- [x] Collective errors
- [x] Tracking progress

Then:

- [x] Add components to design system
- [x] Addresses accessibility/usability considerations
- [x] Works on target devices and browsers

**Comment by jeddy3** [comment]
There are applicable desk research findings in https://github.com/barnardos/design-system/issues/65

**Comment by kelliewellingtons** [comment]
Key finding from [Co-op](http://coop-design-manual.herokuapp.com/styles/forms/form-patterns.html#progress-trackers)

> Progress trackers
> - A progress tracker gives users an indication of how far through a form they are. But they can also get in the way and confuse users.
> - Only use a progress tracker if you have thorough research to support the decision.

**Comment by kelliewellingtons** [comment]
Key findings from [Gov](https://govuk-elements.herokuapp.com/errors/)

> **Errors and validation** 
>
> Ask one question per page, to make it easier for users to recover from errors.
>
> Summarise errors at the top of the page
> You must:
> - show an error summary at the top of the page, so it is visible when the page is refreshed and is immediately read out by assistive technology.
> - include a heading to alert the user to the error
> - link to each of the problematic questions
> - prefix <title> with "Error: "
>
> Highlight errors in forms
> For each error:
> - write a message that helps the user to understand why the error occurred and what to do about it
> - put the message in the <label> or <legend> for the question, after the question text, in red
> - use a red border to visually connect the message and the question it belongs to
> - if the error relates to specific text fields within the question, give these a red border as well

![screen shot 2018-03-16 at 09 42 56](https://user-images.githubusercontent.com/6122118/37513972-730378c8-28fe-11e8-9bdb-96ff7b157e34.png)
