### ISSUE TITLE
[1/2 day] Investigate using cypress for end-to-end tests

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#679]

**Comment by jeddy3** [comment]
Outcome of spike is the decision to use cypress.

It's [recommended by Gatsby](https://www.gatsbyjs.org/docs/end-to-end-testing/):

> Cypress is one of the options when it comes to end-to-end (E2E) testing. Cypress is an all-in-one testing framework focused on E2E testing meaning that you don’t have to install 10 different things to get your test suite set up. 

[Comes with lots of useful DX improvements](https://www.cypress.io/how-it-works/):

> Until now, end-to-end testing wasn’t easy. It was the part developers hated.
Not anymore. Cypress makes setting up, writing, running and debugging tests easy.
