### ISSUE TITLE
Add how to gather data from a selection

### ISSUE THREAD

**Issue by sampling** [barnardos/design-system#68]
_As a user of the design system
I want to know how to gather data from a selection of choices
So that there is a consistent experience across services_

## Description

Submitting data is a fundamental aspect of interfaces.  We've already address single and multiple text freeform input. The next step is picking from a selection.

Website audit:

![selection](https://user-images.githubusercontent.com/808227/37515545-0852a418-2903-11e8-8793-4558a72773ba.jpg)

Consent form audit:

<img width="388" alt="screen shot 2018-03-08 at 15 52 13" src="https://user-images.githubusercontent.com/808227/37515566-1bc22028-2903-11e8-88c1-bdaadc5fdde8.png">

<img width="398" alt="screen shot 2018-03-08 at 15 52 36" src="https://user-images.githubusercontent.com/808227/37515569-1f0c79e0-2903-11e8-9fff-b9783a23da27.png">

## Links and resources

- Desk researching findings from https://github.com/barnardos/design-system/issues/65

## Acceptance Criteria

Document solutions to following concerns:

- [ ] Should it even be a selection, or is freeform better?

Then:

- [ ] Add components to design system
- [ ] Addresses accessibility/usability considerations
- [ ] Works on target devices and browsers

**Comment by jeddy3** [comment]
Findings from [gov](https://govuk-elements.herokuapp.com/form-elements/):

> Avoid using select boxes (drop-down lists) - use radio buttons or checkboxes instead.
> Radio buttons 1. use these to let users choose a single option from a list 2. for more than two options, radio buttons should be stacked
> Checkboxes 1. use these to select either on/off toggles or multiple selections 2. make it clear with words when users can select one or multiple options

**Comment by jeddy3** [comment]
Findings from [co-op](http://coop-design-manual.herokuapp.com/styles/forms/form-inputs.html):


> Radio buttons and checkboxes allow users to select an answer from 2 or more options.

> Use:

> - radio buttons when the user can choose only one answer
> - checkboxes when the user can choose multiple answers

> If you’re using either radio buttons or checkboxes:

> - style them in a way that makes it clear which option or options has been selected
> - display the options a user can choose from top to bottom, not left to right — this makes it quicker for users to scan

> - Where possible, give users the option to indicate that none of the options apply to them. Some users need this to be an explicit option to know that they can move on.

**Comment by jeddy3** [comment]
[Webaim](https://webaim.org/techniques/forms/controls#checkbox) recommended markup from radio and check groups:

```html
<fieldset>
<legend>Select your pizza toppings:</legend>
<input id="ham" type="checkbox" name="toppings" value="ham">
<label for="ham">Ham</label><br>
<input id="pepperoni" type="checkbox" name="toppings" value="pepperoni">
<label for="pepperoni">Pepperoni</label><br>
<input id="mushrooms" type="checkbox" name="toppings" value="mushrooms">
<label for="mushrooms">Mushrooms</label><br>
<input id="olives" type="checkbox" name="toppings" value="olives">
<label for="olives">Olives</label>
</fieldset>
```

**Comment by jeddy3** [comment]
[Webaim](https://webaim.org/techniques/forms/controls#select) on multiselect:

> *It is recommended that multiple select menus be avoided*. Not all browsers provide intuitive keyboard navigation for multiple select menus. Many users do not know to use CTRL/Command or Shift + click to select multiple items. Typically, a set of check box options can provide similar, yet more accessible functionality.

**Comment by kelliewellingtons** [comment]
Findings from [NN](https://www.nngroup.com/articles/checkboxes-vs-radio-buttons/)

> If possible, use radio buttons rather than drop-down menus.
> - Radio buttons have lower cognitive load because they make all options permanently visible so that users can easily compare them.
> - Radio buttons are also easier to operate for users who have difficulty making precise mouse movements.
> 
> Always offer a default selection for radio button lists, for example "None." 
> - Offering users an explicit, neutral option to click is better than requiring the implicit act of not selecting from the list, especially because doing the latter violates the rule of always having exactly one option chosen.
>
> Let users select an option by clicking on either the button/box itself or its label

**Comment by olimj** [comment]
@kelliedesigner @jeddy3 Reading through the research here and the recommendations around avoiding selects, I don't see any discussion around aesthetic and design hierarchy within a form.

For instance, on the title field of a form - it feels like exposing the options (when there's more than say 3) is a little unnecessary visually. A title is common within most signup forms and the options are mostly always uniform - "Mr", "Mrs", "Miss" etc... Exposing these as a radio group would clutter a layout and potentially intimidate a user right at the start of the form filling experience.

Another great example is a 'country' field - the list of options is huge, so it's never going to be practically possible to expose these.

On the findings from NN:
"Avoid dropdown boxes for data that is highly familiar to your users, such as the day, month, or year of their birth" - completely agree with that - things that a personal.

Maybe the recommendations around selects should also be based on the business objectives of the form and the upfront complexity of information a designer knows they will be asking of the user. Completely get that it's important to keep form elements as accessible as possible, but not to the detriment of a user's perception of a form.

@wagg-matt

**Comment by kelliedesigner** [comment]
Hi @olimj, a couple of points to cover here:

**Problems with dropdowns**
There's been a large amount of research done around the use of dropdowns, and evidence has shown they can cause a number of issues:
> - **Lack of Overview** Seeing more than 20 uncategorized options can be bewildering and intimidating, and make it difficult for users to find the input they’re looking for. 
> - **Unnecessary friction** Creating extra steps and work for users for only a couple of options that could simply have been exposed.
> - **Scrolling Issues** Multiple problems are related to scrolling large drop-downs.
> - **Inconsistent UI** The UI of drop-downs differs from browser to browser and OS to OS, and the drop-down will not only look different, but will also work differently.
Source: [Baymard](https://baymard.com/blog/drop-down-usability)

What to Use Instead

**Radio Buttons**
- If you have up to eight options available, we recommend using a list of radio buttons. This may take up vertical space on the form and require scrolling, but this is a better experience for the user, which is important to prioritise over aesthetics. 

**Text Inputs** (with or without autocomplete)
- If you have a problem to solve like a country selector, we recommend using a Text Input with autocomplete, this allows the user to start typing the country and a short and focused list of options will be presented.

This is a great [example of a country selector](https://baymard.com/labs/country-selector) (it's also clever, you can type 'De' to get Germany and 'Nippon' to get Japan)

**Avoid asking for title**
A separate point brought up here, [our guidance](https://design-system.barnardos.org.uk/patterns/gathering-information) states to avoid the use of titles.

Again there has been [research](https://github.com/alphagov/government-service-design-manual/blob/master/service-manual/user-centred-design/resources/patterns/gender-and-sex.md) into this area, and it's been found there is no user need for providing title, and you may offend or upset your users as many people consider that questions about gender or sex are sensitive or inappropriate.
