### ISSUE TITLE
[2 days] Investigate history of global navigation

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#69]
Designs have been created for what the global navigation looks like on the website and the Intranet. 

Investigation into the rationale behind the solution is required as part of collating existing work in order to document universal rules

## Acceptance criteria
- [x] Find out from relevant people about the rationale of the design decisions on the global header
- [x] Document the design decisions here for use on the next issue of adding the global header to the design system

**Comment by ritapatel7** [comment]
It would be good to see the history of global nav as even I'm not aware of the the 'whys'. For FML I've put findings so far on WIKI. Could we do something similar for this? If you could add your findings to WIKI under design systems?

**Comment by kelliewellingtons** [comment]
Screenshots of global header designs for:

Website:
<img width="993" alt="screen shot 2018-03-19 at 11 59 34" src="https://user-images.githubusercontent.com/6122118/37594468-1e179b02-2b6d-11e8-831e-552541e02f79.png">

Intranet:
<img width="985" alt="screen shot 2018-03-19 at 11 58 53" src="https://user-images.githubusercontent.com/6122118/37594479-27546920-2b6d-11e8-9fd6-2f2c8dd38380.png">

**Comment by jeddy3** [comment]
1. [Wayback machine](https://web.archive.org/web/*/http://barnardos.org.uk) has 15 years of barnardos.org.uk navigation.
2. Microsites within:
    - http://www.barnardos.org.uk/commission_us.htm
    - https://www.barnardos.org.uk/fosteringandadoption.htm
    - http://www.barnardos.org.uk/corporate-strategy.htm
    - http://www.barnardos.org.uk/what_we_do/our_work/lgbtq.htm

**Comment by kelliewellingtons** [comment]
Key screenshots from the existing microsites

Commission us:
<img width="1199" alt="screen shot 2018-03-22 at 12 31 45" src="https://user-images.githubusercontent.com/6122118/37770710-3b5ffd14-2dcd-11e8-8813-4f240aee3bdd.png">
![www barnardos org uk_commission_us htm iphone 7](https://user-images.githubusercontent.com/6122118/37770733-455f707e-2dcd-11e8-9fd4-258cfe436371.png)

Our work>LGBTQ
<img width="990" alt="screen shot 2018-03-22 at 12 34 50" src="https://user-images.githubusercontent.com/6122118/37770800-7eb41ece-2dcd-11e8-8088-ddc2cf32944c.png">

**Comment by kelliewellingtons** [comment]
Key screenshots from the history of the barnardos.org.uk navigation

1998
<img width="164" alt="screen shot 2018-03-22 at 12 36 52" src="https://user-images.githubusercontent.com/6122118/37770938-f2afa488-2dcd-11e8-9052-5a1af69fb8c4.png">

2000
<img width="259" alt="screen shot 2018-03-22 at 12 40 23" src="https://user-images.githubusercontent.com/6122118/37771040-3c7866f4-2dce-11e8-8888-fb46e394216f.png">

2003
<img width="168" alt="screen shot 2018-03-22 at 12 41 45" src="https://user-images.githubusercontent.com/6122118/37771097-798cb324-2dce-11e8-94e7-394eb947050b.png">

**Comment by ritapatel7** [comment]
@jeddy3 @kelliewellingtons - I've noticed you mentioned three microsite navigations. I'm not sure if you aware that there are more microsites with their own navs i.e.
[](http://www.barnardos.org.uk/bigtoddle)
[](https://www.barnardos.org.uk/challengeevents) - (go to one of the events/child pages to see the nav)
[](https://www.barnardos.org.uk/induction)
[](https://www.barnardos.org.uk/fosteringandadoption)
[](https://www.barnardos.org.uk/meadowsschool)
[](https://www.barnardos.org.uk/ets-work) - (go to one of the child pages)
[](https://www.barnardos.org.uk/hatday)
And more...

**Comment by jeddy3** [comment]
Spike is complete.

Work continues in https://github.com/barnardos/design-system/issues/2
