### ISSUE TITLE
How to filter content

### ISSUE THREAD

**Issue by kelliewellingtons** [barnardos/design-system#79]
_As a user of the Design System, 
I want to know how to filter content
So that there is a consistent experience across sites_

## Description

![filter](https://user-images.githubusercontent.com/808227/37658126-bb40f1e4-2c44-11e8-8965-2670d74f82ec.jpg)

**Find my local**

<img width="981" alt="screen shot 2018-03-29 at 12 14 31" src="https://user-images.githubusercontent.com/6122118/38086267-92ab523e-334b-11e8-9301-ee5168572221.png">

<img width="986" alt="screen shot 2018-03-29 at 12 15 29" src="https://user-images.githubusercontent.com/6122118/38086273-985c62d6-334b-11e8-8d74-009870732c5f.png">

<img width="437" alt="screen shot 2018-03-29 at 12 15 56" src="https://user-images.githubusercontent.com/6122118/38086277-9d659464-334b-11e8-98e9-78361e877803.png">

**Events**

<img width="415" alt="screen shot 2018-03-29 at 12 21 32" src="https://user-images.githubusercontent.com/6122118/38086363-f51af9a6-334b-11e8-97d2-3d57eff2d31b.png">

<img width="841" alt="screen shot 2018-03-29 at 12 21 53" src="https://user-images.githubusercontent.com/6122118/38086369-fa13bf1a-334b-11e8-9e96-ab616178e581.png">

<img width="977" alt="screen shot 2018-03-29 at 12 22 05" src="https://user-images.githubusercontent.com/6122118/38086375-fd7102c6-334b-11e8-8d21-9d6934545416.png">

## Links and resources
https://www.uxmatters.com/mt/archives/2009/09/best-practices-for-designing-faceted-search-filters.php

https://www.uxmatters.com/mt/archives/2009/02/starting-from-zero-winning-strategies-for-no-search-results-pages.php

## Acceptance criteria
- [ ] Example of requesting data inputs
- [ ] Method of opening filters options
- [ ] Method of closing filter options
- [ ] Way of providing feedback of filters applied
- [ ] Way of clearing filters

In addition:

- [ ] Add component to design system
- [ ] Addresses accessibility/usability considerations (including is accessible for keyboard only use and non JS)
- [ ] Works on target devices and browsers

**Comment by kelliewellingtons** [comment]
Key findings from [UX Matters](https://www.uxmatters.com/mt/archives/2009/09/best-practices-for-designing-faceted-search-filters.php)

> - Decide on your filter value-selection paradigm—either drill-down or parallel selection.
> - Provide an obvious and consistent way to undo filter selection.
> - Always make all filters easily available.
> - At every step in the search workflow, display only filter values that correspond to the available items, or inventory.
> - Provide filter values that encompass all items, or the complete inventory.
>
> What filter paradigm does the user need? 
>
> Single filter value:
> - Links that a user can select for a specific filter or drill down a level in a taxonomy, like a category or department hierarchy
> 
> Multiple filter values:
> - check boxes let customers indicate parallel selections of multiple filter values

**Comment by kelliewellingtons** [comment]
Further detail from [UX Matters](https://www.uxmatters.com/mt/archives/2009/09/best-practices-for-designing-faceted-search-filters.php)

> 1. What filter paradigm does the user need? 
>
> Single filter value:
> Great for displaying multiple levels in a hierarchy like categories
> _"I want to narrow my search results to [category]"_
> - Links that a user can select for a specific filter or drill down a level in a taxonomy, like a category or department hierarchy
> 
> Multiple filter values:
> Great for selecting one or more options for attributes like brands or sizes.
> _"I want to narrow my search results to [category OR category OR category]"_
> - check boxes let customers indicate parallel selections of multiple filter values
>
> Filters don't have to be visible at all times, and can be collapsed behind a label

> 4. At every step in the search workflow, any visible filtering options should reflect only the inventory that is available.

**Comment by olliewright** [comment]
Some links I found useful when I last researched filters (co-incidentally only last month)

You maybe WAY beyond this already but thought I’d share.

(When I looked at the below I switched from using a lot of ‘sort’ columns and turned them into filter options. Their research on giving 'groups' of filters 'titles' also helped me get my head around how different filters need to be clearly labelled for different user-types.

https://medium.com/@laura.cunha/crafting-a-kickass-filtering-ux-beea1798d64b  

https://baymard.com/research/ecommerce-product-lists

https://medium.com/@thierrymeier/filtering-and-sorting-best-practices-on-mobile-61626449cec

[I will detail my key findings - timeline tbd for me to do this in our next sprint planning.]

**Comment by kelliewellingtons** [comment]
Mockup of filter component:
![photo 31-03-2018 14 28 47](https://user-images.githubusercontent.com/6122118/38242337-783c8546-372c-11e8-8dbb-d1694bb06f2f.jpg)

**Comment by jeddy3** [comment]
As queried by Tim, let's look at conditional filters e.g. http://www.barnardos.org.uk/what_we_do/our_work/service-search.htm

**Comment by olliewright** [comment]
Conditional filters you say. You mean like these?

From: http://querybuilder.js.org/ <http://querybuilder.js.org/>

**Comment by jeddy3** [comment]
From [one of](https://medium.com/@thierrymeier/filtering-and-sorting-best-practices-on-mobile-61626449cec) @olliewright's articles:

> When to use: Not everything should be stuffed in filters. Important top level choices which are being made by almost all users are best being made upfront. It also declutters and simplifies the user experience.

**Comment by kelliewellingtons** [comment]
Key findings from [Medium](https://medium.com/@laura.cunha/crafting-a-kickass-filtering-ux-beea1798d64b)

**How to craft a kickass filtering UX**

> **Allow multiple selections**
> Allow multiple selections, allowing the user to narrow down their search quickly especially on slower connections.

> **Use real-world language**
> Filters should be modelled after the actual behaviour of users.

> **Make it clear what filters are active and how to remove them**
> Showing applied filters both in their original position in a separate ‘Applied Filters’ section

> **Make sure filter changes are separate events in the browser**
> Since the content of the page changes, the perception when using filters on desktop web is that there are multiple “pages” instead of a single page with different filters.
> The browser behaviour should match this perception — if a user wants to go back to see a previous filter selection, clicking on the back arrow shouldn’t take them to a completely different page.

**Filtering patterns**
> Airbnb identified the few filters people use the most and displayed them comfortably in the horizontal toolbar. Anything else is tucked under the ‘More’ dropdown, which expands to a full screen.
> Full screen filter views are convenient on mobile when displaying longer sets of filters, since they make for a more focused experience and allow for more screen estate.
