### ISSUE TITLE
Add how display a summary entry point to more detail (card)

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#91]
_As a user of the design system
I want to know how to create an entry point to more detailed information (summary)
So that there is a consistent experience across services_

## Description

Displaying a summary with certain key information and the ability to drill down into further information is a common pattern.

This pattern is used for things like: Search results, event listings, case studies, news listings

<img width="627" alt="screen shot 2018-03-28 at 14 54 30" src="https://user-images.githubusercontent.com/6122118/38033460-f92d6f10-3297-11e8-8d48-55d45e8ae43f.png">

## Links and resources

> - Relates to: #93 and #344 
> - https://material.io/guidelines/components/cards.html
> - https://www.nngroup.com/articles/cards-component/
> - https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary

## Acceptance Criteria

- [ ] What is the key information to surface
- [ ] Consistent solution for each type
- [ ] Optimum content hierarchy for each type
- [ ] Clear differentiation between each type
- [ ] Responsive considerations

Then:
- [ ] Add components to design system
- [ ] Addresses accessibility/usability considerations
- [ ] Works on target devices and browsers

**Comment by kelliewellingtons** [comment]
Mock up of filters for Find my local:
![photo 31-03-2018 14 28 47](https://user-images.githubusercontent.com/6122118/38163679-12551416-34f0-11e8-8dda-c6356468429c.jpg)

**Comment by kelliewellingtons** [comment]
Care Leavers app:
<img width="289" alt="screen shot 2018-06-22 at 15 37 13" src="https://user-images.githubusercontent.com/6122118/41782476-4265ad4a-7632-11e8-9012-11f891ef5df1.png">

**Comment by kelliedesigner** [comment]
Featured entry point on website:
<img width="409" alt="screen shot 2018-08-14 at 14 50 04" src="https://user-images.githubusercontent.com/6122118/44095734-70bc1fb2-9fd1-11e8-9346-45a581086162.png">

<img width="215" alt="screen shot 2018-08-14 at 14 50 21" src="https://user-images.githubusercontent.com/6122118/44095740-74da73a0-9fd1-11e8-876e-8b61ed640bac.png">

**Comment by kelliedesigner** [comment]
https://www.uxpin.com/studio/blog/web-layout-best-practices-12-timeless-ui-patterns-explained/

**Comment by kelliedesigner** [comment]
<img width="742" alt="screen shot 2018-10-26 at 15 51 24" src="https://user-images.githubusercontent.com/6122118/47574278-26ab7680-d937-11e8-908e-20048f8331bd.png">

**Comment by kelliedesigner** [comment]
Current website:

<img width="381" alt="screen shot 2018-10-31 at 09 29 40" src="https://user-images.githubusercontent.com/6122118/47778798-82874e00-dcef-11e8-88c2-f912620578f3.png">

<img width="1129" alt="screen shot 2018-10-31 at 09 28 05" src="https://user-images.githubusercontent.com/6122118/47778809-887d2f00-dcef-11e8-8a8b-2ca1a0dd1ba3.png">

**Comment by kelliedesigner** [comment]
Featured promo box

<img width="799" alt="screen shot 2018-11-02 at 13 29 24" src="https://user-images.githubusercontent.com/6122118/47918080-62988b80-dea3-11e8-9107-995916d6daad.png">

**Comment by kelliedesigner** [comment]
Basic card

<img width="532" alt="screen shot 2018-11-02 at 13 35 10" src="https://user-images.githubusercontent.com/6122118/47918327-2f0a3100-dea4-11e8-906c-7771f7b0c037.png">

**Comment by kelliedesigner** [comment]
Find my local

<img width="1066" alt="screen shot 2018-11-02 at 13 52 36" src="https://user-images.githubusercontent.com/6122118/47919182-a345d400-dea6-11e8-81f0-066c895bb33d.png">

**Comment by kelliedesigner** [comment]
Call out blocks

<img width="1055" alt="screen shot 2018-11-02 at 13 53 26" src="https://user-images.githubusercontent.com/6122118/47919211-ba84c180-dea6-11e8-85a7-e4f94ecc3bec.png">

Intranet call out blocks

<img width="976" alt="screen shot 2018-11-02 at 13 19 22" src="https://user-images.githubusercontent.com/6122118/47919222-c4a6c000-dea6-11e8-86df-d1f30dfc3152.png">

**Comment by kelliedesigner** [comment]
Download

<img width="1002" alt="screen shot 2018-11-02 at 14 02 45" src="https://user-images.githubusercontent.com/6122118/47919774-2d426c80-dea8-11e8-8ee0-0d9574d2ca75.png">

**Comment by jeddy3** [comment]
From [UX Planet](https://uxplanet.org/best-practices-for-cards-fa45e3ad94dd):

> 2. Make the Entire Card Clickable
Follow the Fitts’s Law and allow the user to click/tap any part of the card, not just the text link or image. Larger touch zone substantially improves usability on both touchscreen devices and mouse-based devices.

**Comment by kelliedesigner** [comment]
https://schools.bchydro.com/activities/1/topic

<img width="1163" alt="screen shot 2018-11-05 at 15 29 50" src="https://user-images.githubusercontent.com/6122118/48007516-ba3b2f00-e10f-11e8-8c37-6f6867887a47.png">

**Comment by olimj** [comment]
> From [UX Planet](https://uxplanet.org/best-practices-for-cards-fa45e3ad94dd):
> 
> > 1. Make the Entire Card Clickable
> >    Follow the Fitts’s Law and allow the user to click/tap any part of the card, not just the text link or image. Larger touch zone substantially improves usability on both touchscreen devices and mouse-based devices.

@derekjohnson Good one to chat about today also. Will need to research a little more and better define what a teaser card is for Barnardo's, but this feels a little restrictive to link the entire card. Maybe we have separate definitions for "Teasers" (single link to content and therefore the whole thing is linked) and "Cards" (displays more summary information than a teaser and could have multiple links). One to test...

**Comment by mat-walker** [comment]
> > From [UX Planet](https://uxplanet.org/best-practices-for-cards-fa45e3ad94dd):
> > > 1. Make the Entire Card Clickable
> > >    Follow the Fitts’s Law and allow the user to click/tap any part of the card, not just the text link or image. Larger touch zone substantially improves usability on both touchscreen devices and mouse-based devices.
> 
> @derekjohnson Good one to chat about today also. Will need to research a little more and better define what a teaser card is for Barnardo's, but this feels a little restrictive to link the entire card. Maybe we have separate definitions for "Teasers" (single link to content and therefore the whole thing is linked) and "Cards" (displays more summary information than a teaser and could have multiple links). One to test...

Good one to explore but I can't think of a requirement at the moment where we would have a teaser card with more than one call to action?

**Comment by derekjohnson** [comment]
I don't know enough about making the whole thing clickable to say whether it's a good thing or not. I do know it means you can't select text easily.

There may be a teaser that has a link in the text as well as the main call to action. However there are ways to make that work if the whole thing is a link.
