### ISSUE TITLE
Add how to display multiple summary entry points to more detail (cards)

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#93]
_As a user of the design system
I want to know how to create a list of multiple entry points to more detailed information
So that there is a consistent experience across services_

## Description
Displaying a list of summaries which contain certain key information and the ability to drill down into further information is a common pattern.

This pattern is used for things like: Search results, event listings, case studies, news listings

<img width="778" alt="screen shot 2018-03-28 at 15 20 23" src="https://user-images.githubusercontent.com/6122118/38035112-96f6e412-329b-11e8-8de8-f92de852f854.png">

## Links and resources

- Relates to #91 

## Acceptance Criteria

- [ ] Visual hierarchy
- [ ] Dealing with a large amount of results (relates to #344)

Then:

- [ ] Add components to design system
- [ ] Addresses accessibility/usability considerations
- [ ] Works on target devices and browsers

**Comment by kelliedesigner** [comment]
Website:
![38037671-4082b10a-32a1-11e8-81db-6c25f2c26a9d](https://user-images.githubusercontent.com/6122118/48006694-ece42800-e10d-11e8-8e3a-da9854e1b10a.jpg)

**Comment by jeddy3** [comment]
The new met office website horizontally lists multiple cards across viewport sizes and has horizontal scrolling:
https://beta.metoffice.gov.uk/weather/learn-about/weather/seasons/winter/when-does-winter-start

**Comment by jeddy3** [comment]
Is built. Just needs to be surfaced in DS.

Also related to the `Listing` component https://github.com/barnardos/design-system/issues/460

**Comment by kelliedesigner** [comment]
This has been resolved in #676
