### ISSUE TITLE
Evaluate ease of consuming information by external teams

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#94]
Conduct user research on consumers of the Design System.

**Comment by olliewright** [comment]
@sl33p and Ollie will write a hypothesis (ie. a question / a number of questions) to test against Website Design agencies

**Comment by jeddy3** [comment]
We conducted feedback Q&A session with consumers and we created new issues accordingly.

Superceded by https://github.com/barnardos/design-system/issues/177
