### ISSUE TITLE
Evaluate guidance on gathering and submitting information with service users

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#95]
Conduct user research with young people to evaluate the effectiveness of the guidance on gathering and submitting information.

Relates to: #41 

This could be tested either:

- when this guidance has been applied to a product
- by creating an example product

**Comment by kelliewellingtons** [comment]
mockup and test chosen typeface from #41 as part of this evaluation.

**Comment by kelliedesigner** [comment]
Closing on request from Jess.
