### ISSUE TITLE
How to provide a choice of actions

### ISSUE THREAD

**Issue by joelcarr** [barnardos/design-system#96]
_As a user of the design system
I want to know how to provide a choice of actions
So that there is a consistent experience across services_

## Description

In [consent form builder](https://github.com/barnardos/consent-form-builder) there are currently 'buttons' that initiate a command, such as 'create a new form' or 'print form'. These however break the rules of the 'AttentionGrabbingLink' and do not fit. We need a way to provide a choice of actions to our users in our digital products.

![image](https://user-images.githubusercontent.com/893208/38089562-c4d27da8-3357-11e8-9ea9-0b465debcd53.png)

## Links and resources

- https://github.com/barnardos/consent-form-builder

## Acceptance Criteria

- [ ] Add components to design system
- [ ] Addresses accessibility/usability considerations
- [ ] Works on target devices and browsers

**Comment by kelliewellingtons** [comment]
Closing this issue, as it will be solved as part of issue #122 How to provide a confirmation page.
